ArduPilot/MAVProxy

system.html
Clarify the description of a command.
=> Add missing word in docs for 'time' command.

MAVProxy/modules/mavproxy_map/mp_slipmap.py
Before accessing the attributes of self.mouse_down and newpos, ensure they
exist.
Fixes the following splat I've been observing in the console.
File "/usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_map/
mp_slipmap.py", line 1193, in on_mouse
dx = (self.mouse_down.x - newpos.x)
AttributeError: 'NoneType' object has no attribute 'x'
=> modules: mavproxy_map: fix call to NoneType object

MAVProxy/modules/lib/wxhorizon.py, MAVProxy/modules/lib/wxhorizon_ui.py, MAVProxy/modules/lib/wxhorizon_util.py, MAVProxy/modules/mavproxy_horizon.py
The horizon module has been tweaked to give a few performance improvement on lower performance machines. The ability to set the desired frames per second for updating horizon is provided through the use of horizon-fps set <fps> and horizon get commands. 10 fps is the default, but it is suggested that 5 may be appropriate on some machines. Setting to 0 fps will result in the frame rate being unrestricted.
A bug in the module not unloading when the horizon window is closed, and the window not closing when the module is unloaded, has been fixed.
=> Horizon Module: Performance Improvements. Set horizon fps. Module unload bug fixed.

MAVProxy/modules/mavproxy_msg.py
This patch to ArduPlane logs all statustext messages received from its GCS: https://github.com/ArduPilot/ardupilot/pull/4770
So typing "msg altitude drop" at the MAVProxy prompt will help find that event in the log later.
=> modules: add simple 'msg' module to send statustexts

MAVProxy/modules/mavproxy_wp.py
If someone else has requested waypoints we need to reset
our expected waypoint count, even though we're not doing
the requests
https://github.com/ArduPilot/ardupilot/pull/5595 causes ArduPilot to send these counts if some other GCS (or MAVProxy itself through another codepath (missedit)) resets the waypoint count and mavproxy_wp requests an out-of-bound wwaypoint.
=> wp: honour new wp count sent by autopilot

MAVProxy/modules/lib/wxconsole_ui.py
This PR adds support for click-able hyperlinks in the console window. When double left clicked (or wx event equivalent) a new tab is opened to the url address. This PR is to support the MAVCesium module [issue](https://github.com/SamuelDudley/MAVCesium/issues/4) but I feel it could also be a useful tool to direct users to support pages, documentation or FW downloads.
=> Support dbl left clicking of urls in console window

MAVProxy/modules/mavproxy_param.py
Currently "param help gps_type" will error. This PR fixes that issue
by converting the param name to upper case prior to searching the help
tree.
=> Param: Support non-upper case param names when using param help

MAVProxy/modules/mavproxy_GPSInput.py
This module allows an external application that is determining the position of the vehicle to connect to mavproxy via udp, and forward the position information to the autopilot via GPS_INPUT messages. The information is transported between the external application and MAVProxy via JSON encoded python dictionaries.
=> GPS_INPUT module

MAVProxy/modules/lib/mp_util.py, windows/mavproxy.spec
os.environ['HOME'] crashes under Windows, so we need to use os.environ['LOCALAPPDATA'] instead.
Also added a whole bunch of yaml libraries to the Windows build (required by the joystick module).
=> Windows - fixed pathing error and added yaml module

MAVProxy/modules/mavproxy_DGPS.py
Using GPS_RTCM_DATA messages support fragmenting and reassembling up to 720 bytes of GPS-related data that will be injected into the onboard GPSes. Can be used for RTCM, SBP, UBX, or what-have-you.
=> DGPS Module: Switching DGPS injection to use GPS_RTCM_DATA message.

MAVProxy/modules/mavproxy_speech.py
This is a pretty simple commit.
It adds the 'say' backend, the default text-to-speech engine on mac.
It also adds a skeleton command line command to test the speech engine.
=> MODULE_SPEECH: Adding macOS say backend

MAVProxy/modules/mavproxy_mode.py
As far as I can see there is no reason why it doesn't accept decimal numbers.
I tested it locally with the simulator and it works.
=> Allow decimal altitude to the guided command

MAVProxy/modules/mavproxy_cmdlong.py
the command is actually called 'setspeed' instead of 'speed'. The help information is showing 'speed' which might be confusion. I assume this was called 'speed' before and refactored, but the help message wasn't updated?
=> Update help of "setspeed" command

MAVProxy/mavproxy.py
Old behaviour is that we would listen on port 14550 as if no
serial devices were detected
=> Error-exit if >2 serial devices detected

MAVProxy/modules/lib/wxconsole.py
Fix bug that was introduced when multiprocessing was switched to billiards
=> wxconsole: fix freeze_support

MAVProxy/modules/mavproxy_message.py
Parameters are eval'd:
STABILIZE> Loaded module message
STABILIZE> message MISSION_CLEAR_ALL int(1) int(1)
STABILIZE> Got MAVLink msg: MISSION_ACK {target_system : 255,
target_component : 0, type : 0}
STABILIZE> message SET_GPS_GLOBAL_ORIGIN int(1) float(2.0) float(3.0) float(4.0)
STABILIZE> < GPS_GLOBAL_ORIGIN {latitude : 2, longitude : 3, altitude : 0}
=> mavproxy_message: send arbitrary MAVLink messages

requirements.txt, setup.py
Based on comments in #486 - MAVProxy will crash if it uses any pymavlink older than 2.2.8, so makes sense (and makes the install much smoother) to make this the minimum required pymavlink.
=> Upversioned required pymavlink to 2.2.8

MAVProxy/mavproxy.py, MAVProxy/modules/lib/mp_module.py, MAVProxy/modules/lib/rline.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_link.py
This PR is based on Samuel's https://github.com/ArduPilot/MAVProxy/pull/394/commits
It:
- adds a command to change the link attributes
- corrects an issue in rline
- adds the labels to tab completion
@SamuelDudley I have a concern about the way we're storing these link attributes.  Because we're throwing them directly into the connection object itself, there's the risk of blatting an existing attribute (e.g. `conn.mav`.  Thoughts?
=> Named datalinks

MAVProxy/modules/mavproxy_joystick/joysticks/cypress-spektrum.yml
Fix for #492 
Adding basic support for a [ spektrum dx8 controller ](http://www.spektrumrc.com/Products/Default.aspx?ProdID=SPM8015) with an [OrangeRX usb dongle](https://hobbyking.com/en_us/orange-rx-dsmx-dsm2-compatible-protocol-usb-dongle-flight-simulator.html)
=> added support for Spektrum RX8 with OrangeRX USB dongle

MAVProxy/modules/mavproxy_log.py
master: 286kB/s 255kB/s 270kB/s 276kB/s 264kB/s 245kB/s 265kB/s
bytearray(...)
300kB/s 288kB/s 314kB/s 330kB/s 332kB/s 308kB/s
=> mavproxy_log: construct bytearray rather than string from downloaded data

MAVProxy/mavproxy.py, MAVProxy/modules/lib/mp_menu.py, MAVProxy/modules/mavproxy_fence.py, MAVProxy/modules/mavproxy_kmlread.py, MAVProxy/modules/mavproxy_rally.py, MAVProxy/modules/mavproxy_wp.py, MAVProxy/tools/MAVExplorer.py
- Fixed the ``--version`` commandline argument as reported in https://discuss.ardupilot.org/t/mavproxy-version-check-error/29348/6
- If there's spaces in a file path, MAVProxy/Explorer can't load or save the file. Fixed by adding (optional) quotations around the path returned by ``MPMenuCallFileDialog``
=> A few Windows compatibility fixes

MAVProxy/mavproxy.py
Without this patch, typing:
foo = "
at the mavproxy command prompt is enough to kill the main stdin loop
dead.
=> mavproxy.py: catch shlex exception

MAVProxy/modules/mavproxy_param.py
this prevent rounding when using lat/long and solve an issue on ardupilot autotest.
=> Param: allow 7 digit precision for parameter fetch

MAVProxy/mavproxy.py
@peterbarker 
This fixes the insanity with the tlog files for windows.  Linux obviously didn't exhibit the problem.
Dunno if there are other cases.  The log module looks like it does it right (I was initially confused with the lods module vs tlog writing in the mavproxy.py).
#535
=> fix corrupted tlog files from line ending mangling on Windows

MAVProxy/modules/lib/win_layout.py, MAVProxy/modules/mavproxy_layout.py
If a ``vehicle_name`` is specified in the MAVProxy settings, it will be used to save/load window layout profiles. This allows multiple instances of MAVProxy to have different window layouts.
=> Win_Layout: window layout profiles on a per vehicle_name setting

MAVProxy/modules/mavproxy_map/mp_tile.py, MAVProxy/tools/MAVExplorer.py, appveyor.yml, windows/MAVProxyWinBuild.bat, windows/mavproxy.iss, windows/mavproxy.spec
A couple of things in here:
-Appveyor config file for building Windows installers
-Now using Pyinstaller 3.x for building exe's
-Small updates in MAVProxy/MAVExplorere to support the above
Note this requires an admin to enable Appveyor for this MAVProxy repo.
For reference, see https://ci.appveyor.com/project/stephendade/mavproxy for an example of the outputs.
=> CI - Added Appveyor for building Windows installers

MAVProxy/modules/lib/mp_menu.py
in wx4, the defiinition of TextEntryDialog has changed https://wxpython.org/Phoenix/docs/html/wx.TextEntryDialog.html
=> mp_menu: fix text dialog for wx4

MAVProxy/modules/mavproxy_wp.py
This squelches the warning "not loading waypoints" when working in a
multi-gcs environment
=> mavproxy_wp: summarily ignore mission requests not targeted at us

MAVProxy/modules/mavproxy_adsb.py
As the adsb module is loaded by default, imports requiring cv2 should be delayed until required (the map module is loaded). 
fixes #470
=> mavproxy_adsb: make cv2 requirement optional

MAVProxy/modules/mavproxy_cmdlong.py
This PR fixes a small problem with the mavproxy_cmdlong module's velocity command.
this command sends the [SET_POSITION_TARGET_LOCAL_NED](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_LOCAL_NED ) message but it was not setting some of the [ignore bits](https://mavlink.io/en/messages/common.html#POSITION_TARGET_TYPEMASK) correctly.
In particular it was missing:
- FORCE_SET = 512
- YAW_IGNORE = 1024
- YAW_RATE_IGNORE = 2048
So to add these we increase 455 to 4039.
This has been tested in SITL and it work
=> modules: cmdlong velocity mask fix

MAVProxy/modules/mavproxy_joystick/joysticks/logicool-f310.yml
It won't detect my gamepad(Logicool Gamepad F310) bought in Japan. This PR is may useful for Japanese users.
=> Joystick: support Logicool Gamepad F310

MAVProxy/modules/mavproxy_wp.py
The output of this is... odd, and I really don't understand why those numbers are useful :-)
"20° down" or "80° up" would seem more natural to me...
=> wp: fix division by zero in slope command

MAVProxy/tools/MAVExplorer.py
Without this, I get an error when I type "help" in the console.
=> MAVExplorer.py: use 'sorted()' instead of '.sort()' for Python3 compatibility

MAVProxy/modules/mavproxy_link.py
On python3 we're getting:
bytearray(b'\r')bytearray(b'\n')bytearray(b'\r')bytearray(b'\n')bytearray(b'I')bytearray(b'n')bytearray(b'i')bytearray(b't')bytearray(b' ')bytearray(b'A')bytearray(b'n')bytearray(b't')bytearray(b'e')bytearray(b'n')
Instead of "Init anten", which causes the autotest suite to not work
=> mavproxy_link: correct output of 'linenoise'

setup.py
extras_require allow users to install mavproxy with some extra functionalities:
Like: `pip install mavproxy[server] --user` to install flask and everything necessary for server functionality 
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
=> setup: Add extras_require configuration

MAVProxy/modules/mavproxy_misseditor/mission_editor.py
STABILIZE> Requesting 0 waypoints t=Sat Aug  3 12:44:03 2019 now=Sat Aug  3 12:44:03 2019
Caught exception ('MissionEditorMain' object has no attribute 'console')
File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
self._bootstrap_inner()
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/home/pbarker/.local/lib/python3.6/site-packages/MAVProxy-1.8.8-py3.6.egg/MAVProxy/modules/mavproxy_misseditor/mission_editor.py", line 203, in mavlink_message_queue_handler
=> misseditor: call console on correct object

MAVProxy/modules/mavproxy_misseditor/__init__.py, MAVProxy/modules/mavproxy_misseditor/mission_editor.py
Done incorrectly the mission editor stuffs your  command-line input to MAVProxy (infinite loop in unload, separate PR to fix that up)
Testing for this is:
module load misseditor # window appears
module unload misseditor # window disappears
module load misseditor # window appears again
<click close on that window>
module load misseditor # window appears yet again
@Akshath-Singhal several of these fixes are applicable to the parameter editor
=> Fix mision editor closing issues

MAVProxy/modules/mavproxy_misseditor/mission_editor.py
Stops the waypoint editor getting confused as rally points are transferred with `MISSION_ITEM` messages now.
=> mavproxy_misseditor: ignore non-mission-related mavlink packets

MAVProxy/modules/mavproxy_paramedit/checklisteditor.py, MAVProxy/modules/mavproxy_paramedit/param_editor.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
Added categorical search of parameters with a predefined list of categories.
@tridge  Might need a work around for Flight Modes on Rover. Using only MODE displays extra parameters.
=> Parameditor: Categorical search of parameters

MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_param.py, MAVProxy/modules/mavproxy_paramedit/param_editor.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
@tridge @peterbarker This displays parameter status both in console and in parameditor modules to prevent user from requesting parameter fetch repeatedly as discussed earlier.
PS : Three different commits for three different modules as suggested earlier.
=> Paramstatus: Display current status of received parameters to help with param fetch

appveyor.yml
Attempt to fix the failing builds - The build files will only be saved for master branch builds.
It may still fail, as there is a 50000MB file limit and Appveyor keeps the last 6 months of builds. We may have to wait until Appveyor cleans up some of these old builds.
[Doesn't appear to be a method to manually remove old builds though :disappointed: ]
=> CI: Only keep artifacts for master branch builds

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
Zooming out was always triggering on any amount of rotation due to
(-1/120) being round to -1.
We were always redrawing the map even if we didn't change the zoom level.
Python3 was misbehaving because / was returning a floating point result
for the two integers being divided (Python2 returning an integer).
=> mp_slipmap_ui: correct zooming using mouse wheel

MAVProxy/modules/mavproxy_map/__init__.py
Each vehicle would continuously, pointlessly, clear this layer each time
NAV_CONTROLLER_OUTPUT was returned if not in list of accepted modes.
=> mavproxy_map: remove trajectory layer only once

MAVProxy/modules/mavproxy_map/mp_tile.py, MAVProxy/modules/mavproxy_map/srtm.py
Turns out that srtm and tiles were not actually being cached in Windows. Also, fixed some srtm downloading errors.
=> mavproxy_map: Fix issue on Windows where tiles and srtm were not cached

MAVProxy/mavproxy.py
The ``--setup`` argument now works under Python3 - just needed some str->byte conversions.
=> mavproxy: radio setup now works under Python3

MAVProxy/modules/mavproxy_arm.py
These changes disambiguate some "arm check" uses.
Now:
`arm check all` - sets ARMING_CHECK to 1 (rather than bits individually)
`arm uncheck all` - sets ARMING_CHECK to 0
`arm uncheck LOGGING` - IF ARMING_CHECK was "1", sets it to zero then sets all bits we know about (https://github.com/ArduPilot/MAVProxy/blob/master/MAVProxy/modules/mavproxy_arm.py#L9), *then* sets LOGGING bit to zero.
In the third case, I'm wondering if we should set the first 28 bits or so to 1 instead (rather than just the bits we know about), so newer arming checks aren't disabled by `arm uncheck FOO`.
=> "arm check foo" changes

MAVProxy/modules/mavproxy_console.py
This feature allows user to add fields for displaying data to the console dynamically using the following command:
console_add UNIQUE_IDENTIFIER DISPLAYNAME%variabletype MESSAGE_TYPE EXPRESSION ROW
eg. console_add WPBEAR TARBEAR%u NAV_CONTROLLER_OUTPUT (msg.target_bearing*10) 4
The above command will display the following
=> Console dynamic field display

MAVProxy/modules/mavproxy_log.py
This change makes "log download all" skip existing files.
very useful when there are hundreds of files, and download needs to be resumed.
=> log: skip already-downloaded logs

MAVProxy/tools/mavflightview.py
Fix an error when parsing CMD messages and plotting a mission with the --mission argument, the CMD were still being parsed which caused the loaded mission to ignore certain waypoints.
=> Fixed parsing of CMD when a mission is used

MAVProxy/modules/mavproxy_firmware.py, MAVProxy/modules/mavproxy_map/srtm.py
Found this while trying to fix this error - 
```
File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/home/rajat/.local/lib/python2.7/site-packages/MAVProxy/modules/mavproxy_map/srtm.py", line 173, in createFileListHTTP
parser.feed(data)
File "/usr/lib/python2.7/HTMLParser.py", line 116, in feed
self.rawdata = self.rawdata + data
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
Tested on Ubuntu 18.04, Python2, MAVProxy 1.8.17 (latest master)
This was not a blocking problem, since SITL was still working
=> Change firmware.ardupilot url to https

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
This PR increases the number of decimals in the lat/lon coordinate labels as well as adding more decimals to the distance measurement on the map plot. This allows for precise measurements for checking RTK navigation accuracy
=> MAVFlightView: Increase number of decimals in Lat/Lon and Distance Measurements

MAVProxy/modules/lib/live_graph_ui.py
When graph is called on an array type field, without using an index eg: WHEEL_DISTANCE.distance, MAVProxy goes into a loop of exceptions. This patch checks if the data is of array(list) type and informs the user.
=> Graph: shows error message instead of exception when called on array fields

MAVProxy/modules/mavproxy_console.py
Without a fixed-width font this still jumps left-and-right a little bit,
but without it we jump left and right 4 characters with oscillating
left/right of 0-degrees
=> console: space-pad heading out to three characters

MAVProxy/modules/mavproxy_gopro.py
I may be the only one to ever use this in the last several years, and probably the next several years to come. But it's fixed. Thx Tridge for getting me squared away with this.
- Use vehicle system ID since Solo gimbal is a private channel that ignores broadcast system and component messages.
- Use array for message param values.
=> Fix GoPro module syntax

MAVProxy/modules/mavproxy_link.py
This has been hanging around a long time.  Programmed rather defensively with the fancy stuff wrapped in a `try` block.
e.g.:
```
STABILIZE> Loaded 8 waypoints from Tools/autotest/CMAC-circuit.txt
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
Sent waypoint 0 : MISSION_ITEM {target_system : 1, target_component : 0, seq : 0, frame : 0, command : 16, current : 0, autocontinue : 1, param1 : 0.0, param2 : 0.0, param3 : 0.0, param4 : 0.0, x : -35.362938, y : 149.165085, z : 650.0, mission_type : 0}
```
and
```
Got MISSION_ACK: TYPE_MISSION: UNSUPPORTED
```
and
```
LOITER> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: FAILED
```
and
```
LOITER> APM: Arming motors
Got COMMAND_ACK: …
```
=> mavproxy_link: pretty-print COMMAND_ACK and MISSION_ACK messages

MAVProxy/modules/mavproxy_joystick/joysticks/sz-mypower-ds4.yml
I am using SZ-MYPOWER DS4 Wired Controller in SITL.
This controller is set in MODE2.
Below are the button specifications.
□ Flight Mode 1
× Flight Mode 2
◯ Flight Mode 3
△ Flight Mode 4
R1 Flight Mode 5
L1 Flight Mode 6
R2 RC6 volume
=> joysticks: Add SZ-MYPOWER DS4 Wired Controller

MAVProxy/modules/mavproxy_log.py
It produces an annoying warning
=> mavproxy_log: avoid calling max on empty set

MAVProxy/tools/MAVExplorer.py
Under Python3 looking at these causes a warning as they're specifying an
encoding.
Closes #725
=> MAVExplorer: skip parameter files when looking for graphs

MAVProxy/mavproxy.py
MAVProxy currently doesn't kill its map and console when the controlling tty dies. I suspect this is because multiple SIGHUPs are sent. You can test this behavior by executing mavproxy.py in xterm (xterm -hold -e mavproxy.py --map --console) and then killing the xterm process itself. You could also run mavproxy.py in a tmux pane and kill the pane.
Also, this fixes the map and console persisting when the main mavproxy.py has its input stream closed via ^D.
=> Cleanup map and console after controlling terminal dies

MAVProxy/mavproxy.py
isAlive() has been deprecated in py3.8 and removed in py3.9. is_alive() has been available since python2.7.
See: https://docs.python.org/3.9/whatsnew/3.9.html (ctrl-f isAlive()) for `isAlive()` removal
and https://docs.python.org/2/library/threading.html for `is_alive()` in python2.6 and above.
=> change deprecated isAlive() to is_alive()

MAVProxy/mavproxy.py
The `imp` module has been deprecated and will be removed from python. This patch updates the mavproxy code to use the favored `importlib` module.
The `importlib` module is available in both python2.7 and python>3.4.
=> update from deprecated `imp` module to `importlib`

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_link.py
```
AUTO> link 1 OK (7091 packets, 225278 bytes, 0.03s delay, 56 lost, 0.9% loss, rate:3575B/s)
link 2 OK (6138 packets, 188019 bytes, 0.00s delay, 22 lost, 0.4% loss, rate:3488B/s)
link 3 OK (5416 packets, 172782 bytes, 0.05s delay, 0 lost, 0.0% loss, rate:3658B/s)
```
=> Show number of bytes received and rate on interface in 'link' output

MAVProxy/modules/mavproxy_log.py
you still get an answer back from the vehicle, even if there are not
logs.  The id will not be relevant.
=> mavproxy_log: correct handling of no-logs-on-vehicle case

MAVProxy/modules/mavproxy_joystick/joysticks/spektrumInterLinkDX.yml
I have a Spektrum InterLink DX joystick available for use with Real Flight 9.
I want to use this joystick in SITL.
Spektrum InterLink DX:.
https://www.horizonhobby.com/interlink-dx-simulator-controller-usb-plug-spmrftx1
=> joystick: add Spektrum InterLink DX

MAVProxy/mavproxy.py
Sending from component ID 0 (broadcast) is invalid.
Choice here was essentially random, staying away from MissionPlanner's
number.
Both QGC and MP seem to use `255:190` by default (`255:MAV_COMP_ID_MISSIONPLANNER`) - I don't think we should do the same as it makes testing annoying having all GCS on the same numbers by default.  230 does not have a `MAV_COMP_ID_` assigned to it.
=> mavproxy.py: use 230 for default source component rather than 0

MAVProxy/modules/mavproxy_gimbal.py
Another Python 2 -> 3 issue. Easily fixed though.
=> Gimbal: Add int conversions for Python3

appveyor.yml, windows/MAVProxyWinBuild.bat
Turns out MAVExplorer + pyinstaller + Windows + matplotlib > 3.3 is a bad idea. The Windows build will need to be set to matplotlib 3.2.2 for the time being.
Also tidied up the Windows build script [not used for CI, local builds only]
=> Fix matplotlib-under-windows issue

MAVProxy/modules/mavproxy_map/__init__.py
e.g.
```
map circle 51.874353 14.647401 1.000000 blue
map circle 51.874353 14.647546 1.000000 blue
map circle 51.874353 14.647692 1.000000 blue
map circle 51.874353 14.647837 1.000000 blue
map circle 51.874353 14.647983 1.000000 blue
map circle 51.874353 14.648128 1.000000 blue
map circle 51.874353 14.648274 1.000000 blue
map circle 51.874353 14.648419 1.000000 blue
map circle 51.874353 14.648565 1.000000 blue
map circle 51.874353 14.648710 1.000000 blue
map circle 51.874353 14.648856 1.000000 blue
map circle 51.874353 14.649001 1.000000 blue
map circle 51.874353 14.649147 1.000000 blue
map circle 51.874353 14.649292 1.000000 blue
```
=> Add map circle command for plotting circles

MAVProxy/modules/mavproxy_joystick/joysticks/logicool-f310.yml
This will fix the match pattern for the Logitech F310 Joystick that can be purchased in Japan.
=> mavproxy_joystick: fix Logicool joystick matches pattern

MAVProxy/modules/mavproxy_osd.py
This add support for an OSD module that can be used to manipulate the metadata required by https://github.com/ArduPilot/ardupilot/pull/14203
Commands are:
```
osd param-show 5 1
```
to show param 1 on screen 5
```
osd param-set 5 1 ATC_RAT_PIT_D
```
to set param 1 on screen 5 to ATC_RAT_PIT_D
```
osd param-set 5 6 SERIAL1_PROTOCOL SERIAL_PROTOCOL
```
to set param 6 on screen 5 to SERIAL1_PROTOCOL and use the pre-defined SERIAL_PROTOCOL values
```
osd param-set 5 1 ATC_RAT_PIT_D 0.0 0.1 0.0001
```
to set param 1 on screen 5 to ATC_RAT_PIT_D with min 0.0, max 0.1 and 0.0001 as the increment
=> Add OSD module

MAVProxy/modules/mavproxy_useralerts.py
This is a reference implementation of using ArduPilot's User Alerts in a GCS. Intent is for this to assist other developers in adding User Alerts to their GCS's too.
The getting of the board type via the banner isn't the cleanest way of doing things, but I needed something that wouldn't require a user upgrade of ArduPilot.
Usage:
``module load useralerts`` then ``useralerts check``
Use the ``useralerts set useTest 1 `` to use the example User Alerts database instead of the real database.
@auturgy - FYI
=> Modules: Add User Alerts

windows/mavproxy.spec
This ensures that the Windows installer build collects the joystick configuration files.
=> Windows: Ensure installer collects joystick configuration files

appveyor.yml
This fixes a bug where the ``--version`` argument did not work with the Windows installer.
Now fixed:
=> Windows: Ensure MAVProxy version is stored for installer

MAVProxy/mavproxy.py
This is very different to Windows, where we only look in the .mavproxy
directory (or equivalent)
=> mavproxy.py: look for .mavinit.scr in HOME

MAVProxy/modules/lib/rline.py, windows/mavproxy.spec
Fix and enhancement:
- Fixed a text console failure on Python 3.8 / Windows. This is due to the prompt_toolkit library using asyncio, which was changed in Python 3.8 (see https://github.com/tornadoweb/tornado/issues/2608)
- Removed tcl/tk from Windows build as we don't use in Windows MAVProxy.
=> Python 3.8 / Windows Fix

appveyor.yml
This removes one of the generated artifacts from Appveyor, saving 50% storage.
The removed artifact isn't required, as it's just a capture of part-way through the build process (for debugging purposes, though I've never used it).
=> CI: Use less storage space

MAVProxy/modules/mavproxy_cmdlong.py
Closes https://github.com/ArduPilot/MAVProxy/issues/327
Allows guidance to be given to vehicles with a non-1 system id; several
other commands in here already did the same thing.
=> mavproxy_cmdlong: use self.settings.target_system in place of '1'

MAVProxy/modules/lib/grapher.py
This ensures that the MAVExplorer graphing uses WXPython for rendering, rather than TK.
The live grapher currently forces WXPython (https://github.com/ArduPilot/MAVProxy/blob/master/MAVProxy/modules/lib/live_graph.py#L46), so just copied over the relevent code.
Tested on Windows and Ubuntu20.
=> Modules: Force WXPython backend for grapher

MAVProxy/modules/lib/mp_image.py, MAVProxy/modules/lib/multiproc.py, MAVProxy/modules/mavproxy_map/mp_slipmap.py, MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py, MAVProxy/modules/mavproxy_misseditor/mission_editor.py, MAVProxy/modules/mavproxy_paramedit/param_editor.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
On macOS use `multiprocessing` instead of `billiard` if the Python version >= 3.8.
The custom Queue is still required as macOS does not implement functions needed to support `multiprocessing.Queue.qsize()`.
=> Add support for macOS Catalina / Python3.8+

MAVProxy/modules/lib/wxhorizon.py
One line fix to get the horizon module working on macOS / Python 3.9
This addresses the following error message:
```
MAV> module load horizon
MAV> Loaded module horizon
Cannot access wx from main thread.
File "<string>", line 1, in <module>
File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
return self._bootstrap(parent_sentinel)
File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File …
```
=> Module horizon: fix for macOS / Python 3.9

MAVProxy/modules/lib/magfit.py, MAVProxy/modules/lib/multiproc_util.py, MAVProxy/tools/MAVExplorer.py
This change enables the MagFitUI to display on macOS. It is contingent on pickle support for DFReader https://github.com/ArduPilot/pymavlink/pull/480.
An additional function is provided for the UI child process when the platform is macOS which requires DFReader to be pickled. The alternative would be to retain the existing function and provide additional pickle support for the MagFitUI class.
=> MAVExplorer MagFitUI support for macOS / Windows

MAVProxy/modules/lib/mav_fft.py, MAVProxy/tools/MAVExplorer.py
This PR updates the MAVExplorer `cmd_fft` function to use a new class `MavFFT` which manages the serialisation of the data log between the parent and child processes.
Tested on:
- macOS / Python 3.9
- Windows10 / Python 3.9 (VM)
=> MAVExplorer FFT support

MAVProxy/modules/lib/magfit.py, MAVProxy/modules/lib/mav_fft.py, MAVProxy/modules/lib/msgstats.py, MAVProxy/modules/lib/multiproc_util.py, MAVProxy/tools/MAVExplorer.py
This PR updates enables MAVExplorer > Tools > Stats on macOS / Windows
It also factors out the common code to support child tasks into a small class hierarchy: 
MPChildTask <- MPDataLogChildTask
This reduces much of the duplication in the earlier versions.
Tested on:
- macOS / Python 3.9
- Windows10 / Python 3.9 (VM)
=> MavExplorer: Stats for macOS / Windows

MAVProxy/modules/lib/wxsaildash_ui.py
This PR is a fix for the sailing dashboard to render the fonts without overlap or clipping on windows and linux. 
Apologies - I should have caught this on the main PR, it seems the selected font is resolving differently on each platform and do not size uniformly. What appears correct on macOS is oversized on other platforms.
=> Sail module: update font sizes to suit all platforms

windows/mavproxy.iss
In the installed-Windows-exe MAVProxy, it by default starts in the C:\Program Files(x86}\MAVProxy folder.
MAVProxy will attempt to start writing a logfile there, but Windows will block this action and MAVProxy crashes as a result.
This patch edits the start menu shortcuts to have MAVProxy start in the Documents folder instead, which are writeable.
=> Windows: Ensure MAVProxy shortcuts start in documents folder

MAVProxy/modules/mavproxy_devop.py
```
devop write i2c "" 2 0x40 0x13 1 1
HOLD> Operation 1 failed: 2 (No such bus/device)
```
```
HOLD> devop read i2c "" 2 0x40 0x13 1
HOLD> Operation 1 failed: 2 (No such bus/device)
```
=> mavproxy_devop: provide string descriptions for devop failure codes

MAVProxy/modules/mavproxy_gimbal.py
The usage string in the `gimbal mode` command was missing the `RC` option even though it's supported. This just corrects that and adds the `RC` option into the usage string.
=> gimbal: add missing RC option in gimbal mode usage

MAVProxy/modules/lib/wxsettings_ui.py
This PR is to fix an error in the console settings module (wxsettings) on macOS raised in issue #868.
The main issue was the use of `wx ALIGN_CENTER_VERTICAL` in vertical sizers which raised an exception in wxPython that prevented the window from displaying.
There are two other minor changes to fix issues that surfaced once the window was working: the first is to replace a deprecated event binding call and the second deals with the Python 2 / 3 treatment of unicode. 
These changes tested on:
- macOS Catalina 10.15.7, Python 3.9.1, wxPython 4.1.0
- Ubuntu 18.04, Python 3.6.9, wxPython 4.1.1
- Ubuntu 18.04, Python 2.7.17, wxPython 4.1.1
- Windows 10, Python 3.9.0, wxPython 4.1.1 (successful when run from PowerShell)
- (would benefit from further testing on Windows as tests are not …
=> wxsettings: fix for #868 on macOS

MAVProxy/modules/lib/MacOS/backend_wxagg.py
This PR is to fix an error in the graph module on macOS raised in issue #867
The change is macOS specific and affects `lib/MacOS/backend_wxagg.py`. It updates import directives to account for interface changes in the `matplotlib.backends` module.
These changes tested on macOS Catalina 10.15.7, Python 3.9.1, matplotlib 3.3.3.
My main concern would be support for earlier versions of matplotlib, but we could make it clear in the documentation that a later version is expected and perhaps add matplotlib to `requirements.txt`.
=> live_graph: fix for #867 on macOS

MAVProxy/modules/mavproxy_vicon.py
This commit adds the object_name option to the vicon module. If there are multiple objects being tracked by the vicon system, then you can select the object that corresponds to the UAV. If no option is selected, it will select the first object found.
I have also fixed the coordinate frame conventions, so that the vicon system reports the coordinates in NED, which is what ardupilot expects. There are also some fixes to how quaternions are handled, so that the roll pitch are yaw are correctly reported. I have removed the yaw_offset parameter since it is no-longer necessary.
There is an accompanying pull request on the ardupilot wiki ArduPilot/ardupilot_wiki#3510 to document the correct setup for the vicon system.
=> Vicon: Fix coordinate frame conventions, add object_name option

MAVProxy/modules/mavproxy_ftp.py
```
File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.8.34-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 1003, in periodic_tasks
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_ftp.py", line 753, in idle_task
self.check_read_send()
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_ftp.py", line 711, in check_read_send
if now - self.last_gap_send < 0.05:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
I haven't attempted to understand the flow of control in this module to determine if this should always be being set before being checked.
After this patch is applied master ArduPilot produces this:
```
('Read failed with 1 gaps', 'OP seq:5 sess:1 opcode:129 req_opcode:5 size:2 bc:0 ofs:0 …
```
=> mavproxy_ftp.py: fix exception in idle task

MAVProxy/modules/lib/grapher.py
this fixes the double display of points with multiple instances, for
example:
GPS[0].Spd GPS[1].Spd
it should display the GPS[1].Spd twice
=> grapher: fixed graph of multiple instances

MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_link.py, MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_mode.py
This patch adds support for working with the HIGH_LATENCY2 message:
- New command "hl link on" tells ArduPilot to start emitting the HIGH_LATENCY2 message and stop all other MAVLink streams. Note any non-streamed messages (STATUSTEXT, etc) will continue to be emitted.
- New commend "hl link off" to turn off emission of the HIGH_LATENCY2 message and start all MAVLink streams.
- Support in the map and console modules for displaying data from the HIGH_LATENCY2 message
=> Add support for HIGH_LATENCY2 message

MAVProxy/modules/mavproxy_link.py
=> mavproxy_link: understand Swift-Flyer USB device string

MAVProxy/modules/lib/icon.py, MAVProxy/modules/lib/live_graph_ui.py, MAVProxy/modules/lib/wxconsole.py, MAVProxy/modules/lib/wxconsole_ui.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py, MAVProxy/tools/MAVExplorer.py
This add a simple icon.py script that allow to generate icons for mavproxy with the help of Matplotlib.
There is a two steps loading as we cannot use the wx function before the application is created.
It doesn't bring more dependencies.
Rendering on Ubuntu with xorg. (tried on wayland, but icon aren't displayed, another wayland weirdness)
=> Add icons for console, graph and mavexplorer

MAVProxy/modules/lib/param_help.py, MAVProxy/modules/mavproxy_param.py, MAVProxy/tools/MAVExplorer.py
This makes parameter help available in MAVExplorer.
Examples:
param help ARMING_CHECK
param ARMING* -v
param SERV*ION -v
it displays values and bitmasks with -v, for example:
```
Q_TAILSIT_MOTMX  15.000000 # Motor 1|Motor 2|Motor 3|Motor 4
SERVO1_FUNCTION  36.000000 # Motor4
```
verbose show also works in mavproxy:
param show SER*ION -v
```
SERVO10_FUNCTION 0.0 # Disabled
SERVO11_FUNCTION 0.0 # Disabled
SERVO12_FUNCTION 0.0 # Disabled
SERVO13_FUNCTION 0.0 # Disabled
SERVO14_FUNCTION 0.0 # Disabled
SERVO15_FUNCTION 0.0 # Disabled
SERVO16_FUNCTION 0.0 # Disabled
SERVO1_FUNCTION  4.0 # Aileron
SERVO2_FUNCTION  19.0 # Elevator
SERVO3_FUNCTION  70.0 # Throttle
SERVO4_FUNCTION  21.0 # Rudder
SERVO5_FUNCTION  33.0 # Motor1
SERVO6_FUNCTION  34.0 # Motor2
SERVO7_FUNCTION  35.0 # Motor3 …
```
=> Added parameter help in MAVExplorer

MAVProxy/modules/lib/wxconsole.py, MAVProxy/modules/lib/wxconsole_ui.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/tools/MAVExplorer.py
This patches f1eb929ff11aa78ec379423143db0a67417f7c0f to work under Windows.
Tested in Ubuntu too.
=> Windows: Fix console icons to work under Windows

MAVProxy/modules/mavproxy_cmdlong.py
Using MAV_COMP_ID_SYSTEM_CONTROL breaks some forms of mavlink routing (like the mavlink-router package). More accurate to use the actual target_component instead.
=> Cmdlong: Use target_component instead of MAV_COMP_ID_SYSTEM_CONTROL

MAVProxy/modules/mavproxy_rcsetup.py
=> mavproxy_rcsetup: trim using RC_CHANNELS not RC_CHANNELS_RAW

MAVProxy/modules/lib/graph_ui.py
This patch fixes an ``BrokenPipeError`` exception when running under Windows.
=> Graph: Catch exception in Windows

MAVProxy/modules/lib/graph_ui.py
Closing the graph window results in an exception:
```
pbarker@bluebottle:~/rc/ardupilot(pr/sim-gps)$ MAVExplorer.py logs/00000002.BIN MAV> graph GPS[0].NSats GPS[1].NSats[1]
MAV> Exception in thread main_loop:
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.8.45-py2.7.egg/EGG-INFO/scripts/MAVExplorer.py", line 972, in main_loop
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/lib/graph_ui.py", line 58, in check_xlim_change
except (EOFError, BrokenPipeError):
NameError: global name 'BrokenPipeError' is not defined
```
=> graph_ui.py: avoid exception under Python2 when closing graph window

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_link.py
This PR allows MAVProxy to better handle multiple vehicles on multiple links, for example 5x vehicles on link0 and 2x vehicles on link1.
Previously, MAVProxy would only send the ``request_data_stream_send`` to the active (selected) vehicle. Now MAVProxy will send this message to the relevant (detected) vehicles on each link.
This also exposes a mapping of what vehicles are detected in each link, making it easier for modules to know _which_ links to send a vehicle command on.
@auturgy
=> Better handling of mutiple vehicles & links

MAVProxy/modules/mavproxy_link.py
can get a dictionary-changed error without this.  It's in the idle task
(for where we don't have a complete message), so doesn't happen often.
=> mavlink_link: correct iteration over statustext message ids

MAVProxy/modules/mavproxy_console.py
In flight controllers with mavlink-based ADSB receivers (such as the ADSB Cube carrier board), the receiver will show up as a separate vehicle in MAVProxy (so 2 separate vehicles in the MAVProxy console's "Vehicle" menu), leading to some confusion as to which is the correct vehicle.
This is extra confusing if the flight controller has a different SYSID to the ADSB receiver.
=> Modules: Do not list ADSB system as a vehicle

MAVProxy/modules/mavproxy_paramedit/checklisteditor.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
if the bitmask has gaps then the wrong value was displayed
=> paramedit: fixed bug in bitmask editing

MAVProxy/modules/mavproxy_link.py
The graph module cannot display the RADIO_STATUS items for a SiK radio (together with other status items for the primary target vehicle). The reason for this is that the SiK radio firmware injects RADIO_STATUS mavlink packets having a hard coded sysid/componentid set to '3'/'D' (see mavlink.c macro definition in ardupilot/SiK repository). The graph module is multi_vehicle=false, so it will only get the data for the current primary vehicle and thus the RADIO_STATUS messages with sysid/"vehicle" id 51 don't reach the graph module. This legacy situation warrants special exception handling for the RADIO_STATUS frames.
=> Add special handling for SiK RADIO_STATUS info for graph module

MAVProxy/modules/mavproxy_log.py
`log download 2` where 2 is an empty log creates a div-by-zero error.
=> mavproxy_log: prevent division-by-zero on empty logs

MAVProxy/modules/mavproxy_link.py
This PR allows the user to log link datarate statistics to a csv file in the log directory.
Use ``link dataratelogging on`` and ``link dataratelogging off`` to start/stop logging.
This is useful for debugging any link capacity issues or tuning ArduPilot's stream rates to fit a low bandwidth link.
Example logfile here: [dataratelog.csv](https://github.com/ArduPilot/MAVProxy/files/7577477/dataratelog.csv)
=> Link: Add datarate statistics collection

MAVProxy/modules/lib/mp_util.py, MAVProxy/modules/mavproxy_useralerts.py
The useralerts module retrieves the major/minor/patch version (to compare with the alerts) from the AUTOPILOT_STATUS message's flight_sw_version field. But the decoding of this 32bit integer is incorrectly done with the python hex function which array index iterates through octets not bytes of the flight_sw_version field whereas the encoding in the ardupilot is using encoding as below /1/. The decoding function has been separated out as this might be useful in other places, e.g. the version command in mavproxy doesn't produce any output today (the triggered AUTOPILOT_STATUS message just goes into the log), but that will be for another PR.
/1/
flight_sw_version = version.major << (8 * 3) | \
version.minor << (8 * 2) | \
version.patch << (8 * 1) | \
(uint32_t)(version.fw_type) << (8 * 0);
=> Corrected major/minor/patch decoding of flight_sw_version in AUTOPILOT_STATUS

MAVProxy/mavproxy.py
Without this changes:
```shell
$ mavproxy.py --default-modules="" --master=/dev/ttyACM2 --baudrate=115200
Connect /dev/ttyACM2 source_system=255
File "/usr/local/bin/mavproxy.py", line 4, in <module>
__import__('pkg_resources').run_script('MAVProxy==1.8.46', 'mavproxy.py')
File "/home/gs/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/home/gs/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
exec(script_code, namespace, namespace)
File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.8.46-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 1412, in <module>
File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.8.46-py2.7. …
```
=> Added the ability to set an empty value for modules by default 

MAVProxy/modules/lib/ntrip.py, MAVProxy/modules/mavproxy_ntrip.py
This PR targets #977 . The Fix was slightly more complicated from what I suggested in the issue.
I tested it and it solved the problem of the ntrip restart.
The position in the `NtripClient` is updated every 2 seconds and then sent to the ntrip caster.
=> Resend Position to NTRIP Caster

MAVProxy/mavproxy.py
useful to connect to many links at once
tested with 5 boards like this:
mavproxy.py --console --master /dev/serial/by-id/usb\\*0
=> allow wildcards in --master

MAVProxy/modules/mavproxy_map/__init__.py
```
File "/home/pbarker/.local/lib/python3.6/site-packages/MAVProxy-1.8.46-py3.6.egg/MAVProxy/modules/mavproxy_link.py", line 895, in master_callback
mod.mavlink_packet(m)
File "/home/pbarker/.local/lib/python3.6/site-packages/MAVProxy-1.8.46-py3.6.egg/MAVProxy/modules/mavproxy_map/__init__.py", line 746, in mavlink_packet
(_,_,heading) = self.lat_lon_heading[m.get_srcSystem()]
KeyError: 1
```
... and an unrelated issue where you wouldn't get a heading if you weren't showing ahrspos
=> Fix map bugs with --tracker used in ArduPilot

MAVProxy/modules/lib/grapher.py
This removes this warning that is annoying whenever you graph a new plot. 
See [here](https://stackoverflow.com/questions/69188540/userwarning-marker-is-redundantly-defined-by-the-marker-keyword-argument-when)
Closes: https://github.com/ArduPilot/MAVProxy/issues/986
=> grapher: nuke marker is redundantly defined

MAVProxy/modules/lib/param_help.py
Adds Blimp's parameter data to also be downloaded.
=> Param_help: Add Blimp to param download

MAVProxy/modules/mavproxy_fakegps.py
```
'NoneType' object has no attribute 'mav'
File "/home/pbarker/.local/lib/python3.6/site-packages/MAVProxy-1.8.48-py3.6.egg/EGG-INFO/scripts/mavproxy.py", line 1023, in periodic_tasks
File "/home/pbarker/.local/lib/python3.6/site-packages/MAVProxy-1.8.48-py3.6.egg/MAVProxy/modules/mavproxy_fakegps.py", line 92, in idle_task
self.master.mav.gps_input_send(time_us, 0, 0, gps_week_ms, gps_week, fix_type,
AttributeError: 'NoneType' object has no attribute 'mav'
```
=> fakegps: avoid None-doesn't-have-attribute error

MAVProxy/modules/mavproxy_relay.py
ArduPilot has accepted floats for a very long time for this
=> relay: parse floats for motortest throttle value

MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
```
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py", line 569, in on_redraw_timer
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py", line 543, in redraw_map
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_map/mp_slipmap_util.py", line 306, in draw
File "build/bdist.linux-x86_64/egg/MAVProxy/modules/lib/mp_util.py", line 240, in latlon_round
ZeroDivisionError: float divmod()
```
=> mavproxy_map: avoid division by zero in map zooming

.github/workflows/windows_build.yml, windows/MAVProxyWinBuild.bat
This PR fixes the current Windows build errors in Github Actions.
The issue turned out to be a few package versions not playing nicely together (pip and pyinstaller), so the CI script now ensures it's using the latest pip and pyinstaller.
In addition, pip now recommends using ``python -m pip install .`` in place of ``python setup.py build install`` for building local packages. What I did not realise was that this "recommendation" is in fact _mandatory_ when using the latest version of pyinstaller. :shrug:
=> Fix CI build errors

MAVProxy/modules/mavproxy_checklist.py
For #1056 - this ensures the checklist module GUI cleanly closes on module unload
@AndKe - can you confirm this works for you?
=> Checklist: Close GUI on module unload

MAVProxy/modules/mavproxy_rc.py
ArduPlane uses a 200ms timeout for RC inputs, so 5Hz updates provide an unreliable RC input; prearms fail periodically and RC is shown as unhealthy.
=> mavproxy_rc: increase rc rate to 10Hz

MAVProxy/modules/mavproxy_wp.py
This is required by the changes in <https://github.com/ArduPilot/pymavlink/pull/664>, where the format attribute is removed due to it interfering with messages defining a "format" field.
=> Don't use format attribute of MAVLink_message

MAVProxy/modules/mavproxy_wp.py
=> mavproxy_wp: do not set GET_HOME_POSITION if no mavlink connection

MAVProxy/modules/mavproxy_adsb.py, MAVProxy/modules/mavproxy_cameraview.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_genobstacles.py, MAVProxy/modules/mavproxy_link.py, MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_map/mp_elevation.py, MAVProxy/modules/mavproxy_map/mp_slipmap.py, MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py, MAVProxy/modules/mavproxy_map/mp_slipmap_util.py, MAVProxy/modules/mavproxy_map/srtm.py, MAVProxy/modules/mavproxy_misseditor/__init__.py, MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py, MAVProxy/modules/mavproxy_misseditor/mission_editor.py, MAVProxy/modules/mavproxy_terrain.py, MAVProxy/modules/mavproxy_wp.py, MAVProxy/tools/mavflightview.py, requirements.txt, setup.py
This PR started as adding support for the SRTM1 dataset (https://terrain.ardupilot.org/SRTM1/) and allowing the user to select between the SRTM1 and SRTM3 datasets.
Along the way, I've made the ``terrain`` module the central place for all ground elevation requests where practical to do so. Previously, each module tended to have its own instance of the ``mp_elevation`` object.
The terrain data source can be switched at any time using ``terrain set source [SRTM1, SRTM3]`` or using the main menu on the map window.
The only outstanding issue is the ``misseditor`` GUI needs to be restarted if the terrain data source is changed. I've not quite worked out how to send updates to that GUI.
ping @auturgy
=> Add support for new terrain data sources

MAVProxy/modules/lib/mp_menu.py
this avoids collusions in the 15 bit ID space and re-use of special
IDs that lead to odd icons
=> menu: switch to allocated menu IDs

MAVProxy/tools/MAVExplorer.py
the exception fixes are similar to those already made in mavproxy.py - change to the way we invoke format_exception
shlex raises an exception on bad input, and not catching it makes the MAVExplorer session no-longer-responsive.
param LOG_BACKEND_TYPE\
MAV> No escaped character
File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.50-py3.10.egg/EGG-INFO/scripts/MAVExplorer.py", line 984, in process_stdin
File "/usr/lib/python3.10/shlex.py", line 315, in split
return list(lex)
File "/usr/lib/python3.10/shlex.py", line 300, in __next__
token = self.get_token()
File "/usr/lib/python3.10/shlex.py", line 109, in get_token
raw = self.read_token()
File "/usr/lib/python3.10/shlex.py", line 210, in read_token
raise ValueError("No escaped character") …
=> MAVExplorer.py: correct printing of exceptions, catch shlex exception

MAVProxy/modules/mavproxy_map/mp_slipmap_util.py, MAVProxy/tools/mavflightview.py
Before:
After:
This can be useful when trying to simplify things, particularly Rover missions.
Also sneaks in a little bit of diagnostics for `--colour-source`
=> mavflightview: Add options to not show lines when displaying missions 

MAVProxy/modules/mavproxy_map/mp_tile.py
Change the default value of the `--service` argument from OviHybrid to MicrosoftSat. OviHybrid was removed a few years ago, so attempting to run `mp_tile.py` as a script with no arguments results in the following error:
```
File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 644, in <module>
mt = MPTile(debug=opts.debug, service=opts.service,
File "/nix/store/zs9s8ncp22dpyvnhn858rpvpsch921g3-MAVProxy-1.8.53/bin/.mp_tile.py-wrapped", line 208, in __init__
raise TileException('unknown tile service %s' % service)
__main__.TileException: unknown tile service OviHybrid
```
MicrosoftSat was chosen as the default to match the default parameters of `MPTile`
=> map: remove reference to OviHybrid tile service

MAVProxy/modules/lib/wxhorizon_ui.py
Pitch attitude vertices on the horizon module isn't accounting for roll greater +- 90 degrees.
=> wxhorizon_ui.py: fix pitch nomenclature

.github/workflows/windows_build.yml
This PR allows for auto-upload of the Windows Installer to the "Github Releases" tab.
There are 2 sections to this:
- The latest master will be uploaded as a pre-release
- Any tagged "v``x.y.z``" commits (semantic versioning) will be published as individual releases. So whenever a new MAVProxy version is released, the relevant commit will need to be tagged.
=> CI: Publish Windows Installer to Github Releases

MAVProxy/modules/mavproxy_link.py
This is the case in the type annotation PR (<https://github.com/ArduPilot/pymavlink/pull/666>) in pymavlink.
=> Handle the case where msg.text is a bytes

MAVProxy/modules/mavproxy_messagerate.py
One change introduced in <https://github.com/ArduPilot/pymavlink/pull/664> to change name to msgname. Once this PR is merged, using msgname will avoid a deprecation warning.
=> Use MAVLink_message.msgname wherever possible

MAVProxy/modules/mavproxy_misc.py
Adds support for [MAV_CMD_AIRFRAME_CONFIGURATION](https://mavlink.io/en/messages/common.html#MAV_CMD_AIRFRAME_CONFIGURATION) this command controls landing gear. 
I would consider shorting "landinggear" to something shorter like "gear" as long as it is still easy to be found.
=> Support MAV_CMD_AIRFRAME_CONFIGURATION

MAVProxy/modules/mavproxy_misc.py
`REQUEST_AUTOPILOT_VERSION` is deprecated in favor of `MAV_CMD_REQUEST_MESSAGE` - you get an ACK :-)
=> mavproxy_misc.py: use MAV_CMD_REQUEST_MESSAGE for AUTOPILOT_VERSION

MAVProxy/modules/mavproxy_console.py
Like prearm and proximity, sensor health isn't shown unless we see it as present.
=> console: add entry for flow sensor

MAVProxy/modules/lib/graph_ui.py
use a shallow copy to make graphs independent, avoiding a parsing issue if you start a new graph before the previous graph has displayed
=> graph: prevent interference between graphs in MAVExplorer

MAVProxy/modules/lib/magfit.py
Several users have complained that magfit does not allow resizing the window. I don't know if this is the correct solution, but it does work. 
https://discuss.ardupilot.org/t/magfit-on-mavexplorer-unusable-on-ubuntu-22-04/95764
=> magfit: allow resize

MAVProxy/modules/lib/ntrip.py
Fixes a bug where the ntrip module silently fails if there's an ssl exception when getting the header. Now it will re-request the header if there's an exception.
Tested with ssl and non-ssl connection to ``ntrip.data.gnss.ga.gov.au``
=> Ntrip: Handle ssl exception in header

MAVProxy/tools/MAVExplorer.py
based on MAVProxy's support ofthe same sort of dumping.
I've thought on several occasions I'd already done this...
```
pbarker@fx:~/rc/MAVProxy(pr/mavexplorer-gets-verbose-dumping)$ MAVExplorer.py $TLOG
/home/pbarker/.mavproxy/Blimp.xml Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
/home/pbarker/.mavproxy/Rover.xml Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
MAV> dump --verbose HEARTBEAT
MAV> 2017-10-29 12:44:09.76: HEARTBEAT (id=0) (link=None) (signed=False) (seq=0) (src=255/0)
type: 6 (MAV_TYPE_GCS)
autopilot: 8 (MAV_AUTOPILOT_INVALID)
base_mode: 0
! MAV_MODE_FLAG_CUSTOM_MODE_ENABLED
! MAV_MODE_FLAG_TEST_ENABLED
! …
```
=> MAVExplorer.py: add verbose-dumping of mavlink messages

MAVProxy/modules/mavproxy_wp.py
this was attempting to transfer new waypoints automatically and utterly failing.
So just warn the user that their mission is stale based on what the autopilot is announcing.
Alternative to @magicrub 's https://github.com/ArduPilot/MAVProxy/pull/1152
=> mavproxy_wp: correct re-requesting of waypoints

MAVProxy/modules/mavproxy_cmdlong.py
=> mavproxy_cmdlong: MAV_CMD_REQUEST_MESSAGE turns message name into to id

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_link.py
- factors the watch stuff into a method
- allows --verbose to show details about the messages going back and forth:
Note the additional useful information below if which system we are getting the ACK from:
```
LOITER> watch --verbose COMMAND_ACK
LOITER> Watching ['COMMAND_ACK']
LOITER> 
LOITER> 
LOITER> arm throttle
LOITER> Got COMMAND_ACK: COMPONENT_ARM_DISARM: ACCEPTED
< 2023-03-02 11:32:00.25: COMMAND_ACK (id=77) (link=None) (signed=False) (seq=184) (src=1/1)
command: 400 (MAV_CMD_COMPONENT_ARM_DISARM)
result: 0 (MAV_RESULT_ACCEPTED)
progress: 0
result_param2: 0
target_system: 145
target_component: 230
Got COMMAND_ACK: COMPONENT_ARM_DISARM: DENIED
< 2023-03-02 11:32:00.26: COMMAND_ACK (id=77) (link=None) (signed=False) (seq=16) (src=1/154)
command: 400 (MAV_CMD_COMPONENT_ARM_DISARM) …
```
=> link: add option to watch messages verbosely

MAVProxy/modules/mavproxy_ftp.py
the RFD900x with multipoint firmware does extremely badly at ftp with the normal packet sizes, making param ftp impossible. Using smaller sizes works well and has very little effect on SiK and USB
=> ftp: adjust default read/write sizes

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_wp.py
Sends both the old message and the new command until we know for certain if the autopilot is going to take the command (if it doesn't then we should receive a `MAV_CMD_UNSUPPORTED`)
=> mavproxy_wp: use MAV_CMD_DO_SET_MISSION_CURRENT to set waypoints

MAVProxy/modules/mavproxy_gimbal.py
ArduPIlot has started to send deprecation warnings for the old mount messages and they will be removed at some point.
=> Use mavlink DO_MOUNT_CONTROL in place of old MOUNT_CONTROL message

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
this fixes the error you get when typing "c" into the map
=> mavproxy_map: fix Python3 keys issue

MAVProxy/modules/mavproxy_console.py
AntennaTracker doesn't send VFR_HUD, but does send GLOBAL_POSITION_INT, which has the same heading information in it
=> mavproxy_console.py: use GLOBAL_POSITION_INT for hdg if no VFR_HUD

MAVProxy/modules/mavproxy_map/__init__.py
ArduPilot interprets the command_long frame as relative-alt - we are sending through an AMSL alt of the terrain for the lat/lon.
Using command_int means we remove this problem by actually specifying our frame.
=> map: use command_int when sending ROI

MAVProxy/mavproxy.py
This allows connecting multiple clients to an udp server.
If there is more than one client connected, clients with no communication after `udp-timeout` seconds get removed.
Depends on https://github.com/ArduPilot/pymavlink/pull/574
With timeout=0 (the default), the communication is kept even if the GCS is silent (`set heartbeat 0`)
With timeout higher than zero, the clients that stop talking get removed:
I'm guessing the "Heartbeat OK" is some background task of MAVProxy restoring the communication by sending something (apparently mavproxy sending REQUEST_DATA_STREAM)
=> Create --udp-timeout option

MAVProxy/modules/lib/grapher.py
when you double click and some lines have different valid x ranges we would get a numpy exception. This fixes that and also gets the correct rescale
=> grapher: fixed a y axis rescale bug

MAVProxy/modules/lib/grapher.py
prevents this warning:
warning: Attempting to set identical low and high ylims makes transformation singular; automatically expanding.
=> grapher: prevent zero ypad

MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_link.py, MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_swarm.py, MAVProxy/tools/mavflightview.py
Fixed a problem in which this PR(https://github.com/ArduPilot/ardupilot/pull/21596) caused quadplane's SITL startup to incorrectly display frame types.
=> Vtol: add vtol mav type

MAVProxy/mavproxy.py, MAVProxy/modules/lib/live_graph.py, MAVProxy/modules/lib/live_graph_ui.py, MAVProxy/modules/lib/mp_menu.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_graph.py, MAVProxy/modules/mavproxy_mode.py
for example:
- confirm "Switch to mode MANUAL?" mode manual
- graph degrees(ATTITUDE.roll)<Roll(deg)>
=> added confirm command and allow for labels in live graphs

MAVProxy/modules/mavproxy_fence.py, MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py, MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
when you right click and the position matches multiple objects then check each of the objects rather than just the first one
example with both polygon and wp matching the click point
=> map: fixed menu on map with multiple objects

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_mode.py
this has the advantage that you don't need to be in guided mode to start the command.  Prevents some clunk interactions between pilot and GCS operator as the vehicle does not need to be somewhere safe to loiter before the command can be safely issued.
Tested Copter, Plane and Rover in SITL.  Altitudes appear to be correct.
=> mavproxy_mode: use MAV_CMD_DO_REPOSITION for 'Fly To'

MAVProxy/modules/lib/kmlread.py
this allows it to handle more complex kmz files from google earth
=> kml: make kmlread more robust

MAVProxy/tools/MAVExplorer.py
this allows for things like "help atan" or "help lowpass" for help on graphing functions
=> MAVExplorer: added "help FUNCTION"

.github/workflows/windows_build.yml, MAVProxy/modules/lib/param_help.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py, windows/MAVProxyWinBuild.bat
Companion to https://github.com/ArduPilot/ardupilot/commit/4317a40fef9a54d62078ff64bdf3948404d4cb02, which removed the generation of param defaults.
This PR removes all references to downloading the param defaults.
=> Remove param defaults download

MAVProxy/tools/MAVExplorer.py
... in messages command
Before:
After:
also before (large terminal):
also after (large terminal):
=> MAVEXplorer.py: reassemble STATUSTEXT message chunks into single line ouput

MAVProxy/tools/MAVExplorer.py
When opening a file in MAVExplorer.py, I see the following warnings:
```
/home/simon/.mavproxy/Blimp.xml Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
/home/simon/.mavproxy/Rover.xml Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
``` 
There is already a comment and line in load_graphs function which selects XML files to _not_ to open to avoid this warning. The fix implemented is simply to add "Blimp.xml", "Rover.xml" to this list.
Tested after fix, and warning does not appear, and tool behaves as expected.
=> MAVExplorer.py: Fix XML warnings when opening a file

MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py
Fix for #1162.
Modifies the mission editor's "Command" dropdown to use a custom control (ListCtrl), which has a better layout and visible scrollbars.
Tested on WSL and Ubuntu 22:
@rmackay9 - I'd be interested if this works better for you.
=> misseditor: Better mission command dropdown

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_link.py
this is like moddebug >1 but prints full stack trace rather than just two lines
In the following code a call to a "fail" method was inserted in mavproxy_wp.py in send_wp_requests.  You can see that not limiting the stack trace depth a more useful debug message is produced.
with moddebug 3:
```
STABILIZE> Requesting 0 waypoints t=Fri Jul 28 18:19:44 2023 now=Fri Jul 28 18:19:44 2023 Traceback (most recent call last):
File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/MAVProxy/modules/mavproxy_link.py", line 979, in master_callback
mod.mavlink_packet(m)
File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.65-py3.10.egg/MAVProxy/modules/mavproxy_wp.py", line 164, in mavlink_packet
self.send_wp_requests()
NameError: name 'fail' is not defined …
```
=> mavproxy_link: add moddebug=4 for full stack trace

MAVProxy/tools/MAVExplorer.py
"A value of zero indicates this is the only chunk in the sequence and the message can be emitted immediately."
=> MAVExplorer.py: correct STATUSTEXT coalescing for mavlink1

MAVProxy/modules/lib/mission_item_protocol.py
self.manu may not exist if expython is not present
=> mission_item_protocol: correct behaviour when wxpython not present

MAVProxy/mavproxy.py
In some circumstances forcing the writing of telemetry logs is unhelpful. In my case I'm running a companion computer on the aircraft with a read only filesystem to make it a bit safer to power down at the end of a flight. Most of its mavproxy job is relaying data to a 4G modem and importing ntrip data. It doesn't need to save telemetry logs as the actual GCS on the ground can do that, plus the FC has its own binlogs.
It looks like there was already quasi-support to not write logs (parts of the code that write logs check for the queue before using it) so I've just piggybacked this patch on to that functionality. I've tested that this operates correctly on a read-only filesystem and no longer bails with "ERROR: opening log file for writing".
Thanks for the consideration...
=> option: Implement an option to not write state

MAVProxy/modules/lib/mission_item_protocol.py, MAVProxy/modules/mavproxy_misseditor/mission_editor.py
Steps to reproduce:
```
./Tools/autotest/sim_vehicle.py -v ArduCopter --gdb --debug --map
wp load Tools/autotest/ArduCopter_Tests/copter_terrain_mission.txt
```
Kill the simulation and restart
```
wpedit
```
"Read WPs` in the Mission Editor interface
Right-click in the map and select Mission -> Clear
Observe the error messages in the console:
After this patch no errors in console.
=> Fix warnings after clearing mission

MAVProxy/modules/mavproxy_joystick/controls.py
Improve scale for joystick axis. If inputLow and inputHigh are not -1 and 1, the scaling function must use the actual joystick input values.
=> mavproxy_joystick: Improve scale for joystick axis

MAVProxy/modules/mavproxy_chat/assistant_setup/assistant_instructions.txt, MAVProxy/modules/mavproxy_chat/assistant_setup/get_location_plus_offset.json, MAVProxy/modules/mavproxy_chat/chat_openai.py
This PR includes two small enhancements to the chat module:
1. Instructions to the assistant have been updated to increase the chance that it will set the "frame" field correctly.
2. Add a new get_location_plus_offset function to help the assistant more quickly and easily respond to commands like, "fly 100m North".  Without this the assistant tries to work out the calculation itself each time and this leads to some failures
Both these changes have been tested and work.  Below are some screen shots from a recent test.
I should add that during testing I saw the chat window apparently freeze up twice probably waiting for responses from the Assistant that never arrived.  I haven't seen these freezes before but I assume they are unrelated to these changes and have added this to [the issues …
=> Chat: improve takeoff and fly-to commands

MAVProxy/mavproxy.py, setup.py
=> added --heatbeat-rate

MAVProxy/modules/mavproxy_chat/assistant_setup/assistant_file_checker.py, MAVProxy/modules/mavproxy_chat/assistant_setup/setup_assistant.py, MAVProxy/modules/mavproxy_chat/chat_window.py
This PR includes 3 enhancements and 1 bug fix:
Chat window improvements:
1. Reply window colours are fixed on Windows (user input now correctly appears in red so it can be more easily distinguished from the replies)
2. Blank text is no longer sent to the assistant in cases where the audio-to-text fails or the user simply presses the Send button with no text in the input box
Assistant setup script improvements
3. The assistant setup script re-uses previously uploaded files instead of creating duplicates.  This behaviour can be overridden with the "--upgrade" argument
4. an assistant_file_checker.py script helps find and delete files that were uploaded to OpenAI but never associated with any Assistant.  So far we haven't found any particular problem with having these unused files hanging …
=> Chat: minor GUI and assistant setup enhanecments

.github/workflows/python-cleanliness.yml, MAVProxy/modules/mavproxy_fieldcheck/__init__.py, scripts/run_flake8.py
Similarly to what we do in ArduPilot - enforce that a file meets certain rules iif it has the string `AP_FLAKE8_CLEAN` in it.
=> Enforce flake8 cleanliness on AP_FLAKE8_CLEAN-marked files

MAVProxy/modules/lib/mp_util.py
=> mp_util.py: work around imp module going away in 3.12

MAVProxy/modules/mavproxy_misc.py, MAVProxy/modules/mavproxy_useralerts.py
... MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES has been deprecated for a very long time and can be compiled out of the ardupilot code.  So switch to `MAV_CMD_REQUEST_MESSAGE`
=> Fix useralerts module to use MAV_CMD_REQUEST_MESSAGE

MAVProxy/modules/mavproxy_chat/__init__.py, MAVProxy/modules/mavproxy_chat/assistant_setup/assistant_file_checker.py, MAVProxy/modules/mavproxy_chat/assistant_setup/setup_assistant.py, MAVProxy/modules/mavproxy_chat/chat_openai.py, MAVProxy/modules/mavproxy_chat/chat_voice_to_text.py, MAVProxy/modules/mavproxy_chat/chat_window.py
On the last PR @peterbarker brought up some flake8 fixes so I think this resolves all but one.  It doesn't like the long line in chat_openai.py (line 612).
This has been lightly tested in SITL and seems OK.
=> chat: flake fixes

MAVProxy/modules/lib/wxhorizon_ui.py
Fixes: https://github.com/ArduPilot/MAVProxy/issues/1271
The `matplotlib.patches.RegularPolygon` initialiser requires a keyword arg rather than positional arg for the radius:
https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/patches.py#L895-L897
Tested with `matplotlib==3.7.4` for backwards compatibility and `matplotlib==3.8.2`.
=> horizon: use keyword arg for radius

MAVProxy/modules/lib/MacOS/backend_wxagg.py
Fixes #1304 
Remove deprecated and unused imports from the macOS `wx` backend.
Summary of deprecated APIs:
- https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#removal-of-deprecated-apis
Tested with `matplotlib==3.7.4` for backwards compatibility and `matplotlib==3.8.2`.
=> macOS: remove deprecated and unused imports

MAVProxy/modules/lib/rline.py, MAVProxy/tools/MAVExplorer.py
Imagine the `<tab><tab>`s in the following:
```
MAV> dump 
AHR2     DU32     IMU      MAVC     NKF3     NKQ2     PAY5     SRTL
ATT      EV       IMU2     MAV[3]   NKF4     NKT2     PM       TERR
BAR2     FMT      IMU3     MODE     NKF5     ORGN     POS      UNIT
BARO     FMTU     ISBD     MOTB     NKF6     PARM     POWR     VIBE
BAT      GPA      ISBH     MSG      NKF7     PAY1     PPO2     __MAV__
CMD      GPS      MAG      MULT     NKF8     PAY2     RATE     
CTUN     GUID     MAG2     NKF1     NKF9     PAY3     RCIN     
DSF      HEAT     MAV      NKF2     NKQ1     PAY4     RCOU     
MAV> dump I
IMU   IMU2  IMU3  ISBD  ISBH  
MAV> dump I
```
=> Correct tab completion of the dump command commandline

MAVProxy/modules/lib/rline.py, MAVProxy/tools/MAVExplorer.py
I very much like PR #1303 from @peterbarker - I have often typed dump and pressed tab to be met with nothing!
However, when using the code from this update, I spotted a couple of things that were not quite as I expected...
- It looks like you meant to link the dump command to new the (MESSAGETYPE) completion that you created, but used (VARIABLE) by mistake, so I changed this.
- The completion includes message instances as well as messages (i.e. both IMU and IMU[1]), but dump only works with the name without instance, so I updated the filter to remove them.
And nothing to do with the previous PR:
- When pressing tab on something like "graph BAT[" it was getting an error, so I updated the partially open array regex to use * instead of + for the text after "[" (i.e. allowed to be empty).
- …
=> MAVExplorer: don't show instances with dump tab completion

MAVProxy/modules/lib/mp_module.py, MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_fence.py, MAVProxy/modules/mavproxy_link.py, MAVProxy/modules/mavproxy_map/__init__.py
This adds the appropriate filters so that ``MAV_COMP_ID_PERIPHERAL`` devices can be used without confusing MAVProxy.
EDIT:
This PR now allows any MAVLink accessories (same sysid as flight controller, different component id) to:
a) Not confuse MAVProxy if the accessory is sending a heartbeat
b) Selecting the accessory in the console->vehicle->select menu correctly filters packets from the accessory to non-multi-vehicle-aware modules.
=> Better filtering of MAVLink components

MAVProxy/modules/mavproxy_fieldcheck/__init__.py
this was enforcing a non-existant fence action on Plane...
=> fieldcheck: adjust required fence action based on vehicle type

MAVProxy/modules/lib/msgstats.py, MAVProxy/modules/lib/multiproc_util.py
When looking at something else, I noticed that when using the 'stats' command in MAVExplorer with either DF text logs or TLOGs it raises an Exception for different reasons.
* DF Text logs: `KeyError: 128`
* TLOGs: `ERROR in command []: 'mavmmaplog' object has no attribute 'filehandle'`
It looks like TLOGs were not supported, but should at least have given a nicer error message. But while here, I have added the support for them.
Summary of changes needed:
For DF text logs:
* message name rather than message id is used to index the counts dict, and it is unset for messages that are never seen.
* needs: https://github.com/ArduPilot/pymavlink/pull/906
For TLOG:
* As there isn't a formats attribute on the mavmmaplog class (as used for Tlogs), I am counting message instances rather than size in …
=> MAVExplorer: Fix stats command for DF text and TLOG logs

MAVProxy/tools/MAVExplorer.py
This PR provides the MAVExplorer side of: https://github.com/ArduPilot/pymavlink/pull/911
It enables the use of the '--verbose' argument on the dump command for DF logs.
I use hasattr to check for dump_verbose function to avoid exception in case an older pymavlink is installed.
Example of output:
```
MAV> dump --verbose POS
2023-12-30 09:59:58.079: POS
TimeUS: 37126810 µs
Lat: 33.810313 deglatitude
Lng: -118.393867 deglongitude
Alt: -0.14000000059604645 m
RelHomeAlt: -0.535001277923584 m
RelOriginAlt: -0.21500125527381897 m
```
=> MAVExplorer: Add verbose output of DF log messages

MAVProxy/modules/mavproxy_rc.py
```
rc 3 1000
MANUAL> rc 4 65535
MANUAL> rc status
MANUAL> 
1: 0      (no override)
2: 0      (no override)
3: 1000
4: 65535      (ignored)
5: 0      (no override)
6: 0      (no override)
7: 0      (no override)
8: 0      (no override)
9: 0      (no override)
10: 0      (no override)
11: 0      (no override)
12: 0      (no override)
13: 0      (no override)
14: 0      (no override)
15: 0      (no override)
16: 0      (no override)
17: 0      (no override)
18: 0      (no override)
```
=> mavproxy_rc: add status command

MAVProxy/tools/MAVExplorer.py
This PR updates the MAVExplorer lookup tables for events (as used on EV messages) and subsystems (as used on ERR messages), to align with the latest list in [AP_Logger.h](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Logger/AP_Logger.h).
I have also re-worked the lookup table of subsystem-specific error codes, to allow them to be included when running the 'messages' command. Note that the previous list was unused, and only the number was shown.
The list now uses the subsystem name (with optional wildcard) to select the relevant set of susbsytem-specific codes, falling through to the generic ones if necessary, and showing the number if all else fails.
Example output from testing with ArduSub-ArmFeatures-00000003.BIN from Autotest:
```
2023-12-30 09:59:22.779 Error: Subsys …
```
=> MAVExplorer: Update lookups for EV & ERR messages

MAVProxy/tools/MAVExplorer.py
This PR allows autocompletion in MAVExplorer when using "dump --verbose \<tab\>".
Previously the autocompletion was added for "dump \<tab\>", but with "--verbose" argument it did not work.
Tested on my local version.
=> MAVExplorer: Autocompletion on dump --verbose command

MAVProxy/tools/mavflightview.py
so "map VEH" works with dual-vehicle logs
=> MAVExplorer: allow VEH msg to behave like GPS

MAVProxy/modules/lib/ntrip.py, setup.py
The MAVproxy NTRIP client does not work with several NTRIP casters, because the GGA messages are sent in an incompatible format. this is described in #1131 
This PR solves that problem, by using the same library for gga generation that [pygpsclient](https://github.com/semuconsulting/PyGPSClient) uses ([pynmeagps](https://github.com/semuconsulting/pynmeagps)), which I experienced to be working with all casters. 
The ntrip client of pygpsclient works quite well, so I might open an Issue in the future to request that the MAVproxy ntrip could be refactored as a wraper of that NTRIP client. It has more active developers than the built-in NTRIP Client of MAVproxy.
For now, this PR should provide a solution that is tested with skylark and I am confident that it also solves the problem with …
=> NTRIP: use pynmeagps for correct gga generation

MAVProxy/modules/mavproxy_misc.py, MAVProxy/tools/MAVExplorer.py
IMU decoding with devid expects the parameter to be `INS_GYRn` or `INS_ACCn`.
Since more than 3 IMUs were added, the parameter in the flight controller is `INSn_GYR` and `INSn_ACC`.
This opens up `devid` to be able to decode all the IMUs available.
=> Show all IMUs with devid

MAVProxy/modules/mavproxy_GPSInject.py
I changed the AssistNow download on the firmware server so it is now only fetching 1 day ahead. This means the file is quite small, so no need to parse it and select the right records, we can just send it all to the GPS
Usage:
- module load GPSInject
- gpsinject start
=> GPSInject: module for injecting AssistNow data

MAVProxy/modules/mavproxy_chat/chat_window.py
Before input key field for api key was exposed
After changes input key field for api key
=> Chat: added password input field for api_key

MAVProxy/tools/MAVExplorer.py
The aim of this PR is to start making use of the LogMessage xml files in MAVExplorer.
This PR adds the commands "logmessage download" and "logmessage help <msg>" to MAVExplorer.
The download command will download all LogMessage XMLs to the user's .mavproxy folder.
The help command calls  mlog.metadata.print_help(msg) method on the new DFMetaData class (links to PR https://github.com/ArduPilot/pymavlink/pull/929).
The DFMetaData class is implemented in DFReader.py file, within pymavlink, so that other tools, such as mavlogdump can access the meta data on a loaded DF file without a dependency on MAVProxy. For example, to provide the enum strings and bitmask information when doing "mavlogdump --verbose".
Any call to mlog.metadata is protected with hasattr(mlog,'metadata') in case mlog is a …
=> MAVExplorer: Add logmessage download and help commands, using meta-data from autotest web site

MAVProxy/mavproxy.py, MAVProxy/modules/mavproxy_link.py
In some debugging applications, I use more retries than the default 3 that are given.
This exposes retries to the command line, allowing to increase how many attempts before mavproxy gives up.
=> MAVProxy support retries from cmd line

MAVProxy/modules/mavproxy_map/__init__.py
these aren't used all that much, and grouping them together saves space on the top-level menu.
Also, hitting set-home at runtime is bad, even with the confirmation.
=> map: move setting of home and origin into a submenu

MAVProxy/modules/mavproxy_map/__init__.py
prior to this patch you had to know the lat/lng you wanted a circle.
After this patch you supplying 1 or 2 arguments only will assume you want the circle at the click location.
Usage: map circle <lat> <lon> <radius> <colour>
Usage: map circle <radius> <colour>
=> mavproxy_map: enhance map_circle to be able to consume click position

MAVProxy/modules/lib/wxrc.py, MAVProxy/modules/mavproxy_rc.py
As per the below screenshot, this adds GUI windows for showing the current values of the RC inputs and Servo outputs. Useful for debugging any issues with inputs and outputs.
It can be launched via ``rc guiin`` or ``rc guiout`` to show the RC in and Servo out windows respectively. Otherwise, there is a menu for them in the console (rc menu).
Tested in SITL.
=> Add a GUI for showing RC and servo channels

MAVProxy/modules/mavproxy_speech.py
```
MAV> Detected vehicle 1:1 on link 0
Using speech backend 'speechd'
File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
cls(buf, protocol).dump(obj)
File "/usr/lib/python3.10/multiprocessing/connection.py", line 968, in reduce_connection
df = reduction.DupFd(conn.fileno())
File "/usr/lib/python3.10/multiprocessing/connection.py", line 170, in fileno
self._check_closed()
File "/usr/lib/python3.10/multiprocessing/connection.py", line 136, in _check_closed
raise OSError("handle is closed")
OSError: handle is closed
```
=> speech: add awful hack around Python threading problem

MAVProxy/modules/mavproxy_mode.py
pushes Copter forward or backward without changing the yaw
=> mavproxy_mode: add 'guided forward METRES' subcommand

MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py
somehow this changed to a string... so just cope with that
=> misseditor: correct display of distance/gradient

MAVProxy/modules/lib/msgstats.py
The idea of this PR is to add the message description to the 'stats' command in MAVExplorer, using the downloaded XML metadata.
When I was first getting the hang of looking at logged data, I found myself using the stats command as a good to way to have an index of what messages exist, but the 4-letter names can take a while to get the hang of, so I thought that something like this would have made it easier!
Output is like this:
```
MODE  0.00%  [vehicle control mode information]
ARM   0.00%  [Arming status changes]
EV    0.00%  [Specifically coded event messages]
AUXF  0.00%  [Auxiliary function invocation information]
VER   0.00%  [Ardupilot version]
LAND  0.00%  [Slope Landing data]
DSF   0.03%  [Onboard logging statistics]
TERR  0.03%  [Terrain database information]
FMTU  0.03% …
```
=> MAVExplorer: Add message descriptions to stats command

MAVProxy/mavproxy.py
A command-line of kml load "/home/pbarker/e0/sypaq/carbonix-flying-sites/Carbonix Flight Areas.kmz" gets turned into a 3-element list.
Past this PR the last element will not be enclosed in quotes, which means that modules don't need to do their own quote-stripping
=> mavproxy.py: strip enclosing quotes from parsed shlex results

MAVProxy/modules/mavproxy_map/__init__.py
currently we only check for events when we receive mavlink packets.
That's a problem for the right-click menu option "Google Maps Link", because often when you want that option you are not actually getting packets from the vehicle....
Process packets in the idle loop as well as after receiving a mavlink packet.
=> map: check events in idle loop

MAVProxy/mavproxy.py
message is not an attribute of e (any more?)
Before:
```
MANUAL>   File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.70-py3.10.egg/EGG-INFO/scripts/mavproxy.py", line 756, in process_stdin
MANUAL> AttributeError: 'ValueError' object has no attribute 'message'
MANUAL> Unknown command 'File "/home/pbarker/.local/lib/python3.10/site-packages/MAVProxy-1.8.70-py3.10.egg/EGG-INFO/scripts/mavproxy.py", line 756, in process_stdin'
Unknown command 'AttributeError: 'ValueError' object has no attribute 'message''
```
after:
```
MANUAL> Caught shlex exception: No closing quotation
```
=> mavproxy.py: correct printing of shlex exception

MAVProxy/modules/mavproxy_kmlread.py
the addition of the counter for the layer name broke the population of the "current layers" list
=> Correct initial KML checkbox values

MAVProxy/modules/mavproxy_battery.py
Shows the per-cell voltage when the user has set the number of battery cells.
Not sure if maybe it should still show the full battery voltage when this is set?
Maybe an option?
Tested in SITL but not with a real vehicle (yet).
=> Show per-cell voltage when number of cells is given.

.github/workflows/windows_build.yml
Fixes the issue of stable releases not being generated. Using a different GitHub action appears to fix it.
=> CI: Fixed Windows release building

MAVProxy/mavproxy.py
simple factors this method out.  NFC.
Considering adding a "--no-startup-scripts" command-line option.
=> mavproxy.py: factor out a run_startup_scripts method

MAVProxy/modules/mavproxy_chat/chat_openai.py, MAVProxy/modules/mavproxy_chat/chat_window.py
This PR adds a cancel feature to cancel the active run on Open AI, i.e. it helps cancelling the active prompt given by user.
=> Chat: feature to cancel active runs

MAVProxy/modules/mavproxy_chat/assistant_setup/setup_assistant.py
This updates the setup_assistant.py script which is used to create assistants on the OpenAI server.
The changes include:
- Assistant uses "gpt-4o" which is the latest model from OpenAI
- the "code interpreter" tool is disabled.  this was never required actually
- mavlink xml files are converted to json before uploading.  the assistant is not capable of parsing xml files it seems ([see here](https://platform.openai.com/docs/assistants/tools/file-search/supported-files)) so the xml files were never actually being used.
- uploaded files are added to a "vector store".  This is because of an API change and was not required previously
This has been tested 
stant_setup (chat-assistant-setup-4o)$ python setup_assistant.py --upgrade
Starting assistant setup
setup_assistant: parsed function file: …
=> chat: update setup_assistant to use gpt-4o

MAVProxy/modules/mavproxy_link.py
issues TIMESYNC requests and prints results
A CubeOrange connected via USB:
```
ACRO> ping
ACRO> ping response: 3.075ms from=1/1 in-link=0 out-link=0
```
Multiple links to a SITL instance:
```
STABILIZE> link list
STABILIZE> 2 links
0: :14550
1: localhost:17000
ping
STABILIZE> ping response: 6.180ms from=1/1 in-link=0 out-link=0
ping response: 6.461ms from=1/1 in-link=0 out-link=1
ping response: 6.886ms from=1/1 in-link=1 out-link=0
ping response: 6.996ms from=1/1 in-link=1 out-link=1
```
Uses `console`:
=> mavproxy_link: add "ping" command

MAVProxy/modules/mavproxy_map/__init__.py
Notably this removes the vehicle icon from the map when you change the map settings.
So if you `map set showgpspos 0` then the GPS icon will disappear, rather than just not be updated.  Similary for ahrspos, simpos etc etc.
This factoring should also allow us to add another map setting to add text to each icon to make it clear what it is representing, eg.
=> map: factor out methods for displaying vehicle on map

MAVProxy/modules/mavproxy_chat/chat_openai.py, MAVProxy/modules/mavproxy_chat/chat_window.py
This PR adds the streaming feature by Open-AI assistants API.
Previous: Chats were concatenated together and displayed on screen, the wait time for replies in that approach was too long.
Streaming enables the communication of server sent events, which reduces the latency and wait time.
Below is a sample test-video displaying the working of stream.
https://github.com/ArduPilot/MAVProxy/assets/106031961/aabc933c-73a0-448a-8c85-4c6566babca5
=> chat: enabled chat streaming feature

MAVProxy/tools/MAVExplorer.py, MAVProxy/tools/mavflightview.py
this allows mavextra to construct new mappable objects with Lat and Lng fields, allowing for derived positions from logs
this also generalises and simplifies the handling of instances
for example:
this uses the following mavextra function:
```
def pos_offset(GPS,offs_N,offs_E):
latlon = mp_util.gps_offset(GPS.Lat,GPS.Lng, offs_E, offs_N)
return PosObj(latlon[0],latlon[1],GPS.Alt)
```
=> MAVExplorer: allow arbitrary expressions to be plotted on the map

.github/workflows/windows_build.yml, setup.py, windows/MAVProxyWinBuild.bat
Add a [recommended] section to setup.py, where we can put all the optional module requirements.
Can use this via ``pip install mavproxy[recommended] --user``
Fixes #1423
=> Add recommended modules

MAVProxy/modules/mavproxy_map/mp_tile.py
Two things addressed here:
-  A number of tile services no longer worked. In some cases a URL rename was needed. In other cases, the provider no longer existed.
-  Added an url-agent to map tile download requests, as the default agent for python3 urllib was getting blocked.
NB: Was unable to test the ``GoogleChina``, ``StatkartTopo``, ``StatkartBasemap`` and ``Eniro DK,NO,SE,FI,PL`` as they might be geo-blocked (at leat in Australia)?
Fix for #1425
=> Modules: Update tile services

MAVProxy/mavproxy.py
The line: `master.port.inWaiting()` is causing a SerialException when a reboot is sent to the flight controller from the console.
This change has been tested in windows and linux, it does not appear to have an effect on linux. The exception does not trigger in linux, but does on windows.
=> MAVProxy: fixed reconnection of serial port on windows after reboot

MAVProxy/modules/mavproxy_map/mp_tile.py
Eniro renamed to Gulesider and got HTTPS.
Statkart maps: new, faster servers.
Svalbard maps added.
=> Modules: updated nordic map sources

MAVProxy/mavproxy.py
may prevent an odd threading exception in Python
=> mavproxy.py: exit logging thread if cltr-c exit flag is set

MAVProxy/modules/mavproxy_chat/assistant_setup/assistant_instructions.txt
Previously said that lat was short for longitude, but I changed it to lon, which may fix some problems with the assistant when it comes to certain prompts from the user.
=> chat: Changed longitude is "lat" to longitude is "lon"

MAVProxy/modules/lib/ntrip.py
I ran into an issue getting the popular RTK base station system, [rtkbase](https://github.com/Stefal/rtkbase) working with MAVProxy. Doing some deeper analysis, it looks like rtkbase uses the `str2str` utility provided in the popular [RTKLIB](https://github.com/tomojitakasu/RTKLIB) project.
What I found is that the str2str NTRIP caster returns a response that looks like this:
```
ICY 200 OK
(rtcm-bytes)
```
Notice how the server response does not include any headers and just goes straight to the response body without a blank line? Because of this, the ntrip.py library will never find a blank line, and `self.found_header` will never equal `True` which means the ntrip library will always be "stuck" waiting for headers.
At first I debated whether or not this library should be updated in …
=> ntrip: Added support for NTRIP Rev1 servers

MAVProxy/modules/mavproxy_chat/chat_voice_to_text.py, MAVProxy/modules/mavproxy_chat/chat_window.py
This PR adds a push to record feature i.e. it will record the audio on mouse left key press down and stop the recording on key release.
=> chat: push to record

MAVProxy/modules/mavproxy_link.py
If there are multiple components sending heartbeats, MAVProxy can get confused, lock onto the wrong one, and fail to receive any messages from the real autopilot.
There is a function in pymavlink, `probably_vehicle_heartbeat`, which can check for this since this commit https://github.com/arduPilot/pymavlink/commit/67669c3b84a1f0d7792c5faa487230b94a628135.
However, MAVProxy does not use `probably_vehicle_heartbeat` (at least not for this purpose), having its own version called `heartbeat_is_from_autopilot` in the link modoule.
The corresponding check is present in that function! However (x2), it incorrectly compares an integer against a string, which never matches.
This PR changes the strings to integer constants.
Disclaimer: I am employed by Exyn Technologies, an Ardupilot partner
=> link: fix non-vehicle heartbeat filter

MAVProxy/modules/lib/grapher.py
/home/pbarker/.local/lib/python3.12/site-packages/MAVProxy-1.8.71-py3.12.egg/MAVProxy/modules/lib/grapher.py:604: SyntaxWarning: invalid escape sequence '\['
=> modules: grapher.py: fix regex-escape-sequence warning

MAVProxy/modules/lib/param_help.py
After:
```
param help GUID_OPTIONS
STABILIZE> GUID_OPTIONS: Guided mode options
Options that can be applied to change guided mode behaviour
Bitmask: 
0 : Allow Arming from Transmitter
2 : Ignore pilot yaw
3 : SetAttitudeTarget interprets Thrust As Thrust
4 : Do not stabilize PositionXY
5 : Do not stabilize VelocityXY
6 : Waypoint navigation used for position targets
7 : Allow weathervaning
```
Before:
```
STABILIZE> param help GUID_OPTIONS
STABILIZE> GUID_OPTIONS: Guided mode options
Options that can be applied to change guided mode behaviour
Bitmask : 0:Allow Arming from Transmitter,2:Ignore pilot yaw,3:SetAttitudeTarget interprets Thrust As Thrust,4:Do not stabilize PositionXY,5:Do not stabilize VelocityXY,6:Waypoint navigation used for position targets,7:Allow weathervaning
```
=> param_help.py: pretty-print Bitmask in eg. 'param help GUID_OPTIONS' output

MAVProxy/modules/lib/param_help.py
stop parsing the Bitmask text field if we don't need to
=> param_help.py: use bitmask subtree if available

MAVProxy/tools/MAVExplorer.py, MAVProxy/tools/mavflightview.py
We used to get the uploaded mission by default; restore that behaviour.
=> Correct plotting of mission in MAVExplorer

MAVProxy/modules/mavproxy_wp.py
=> mavproxy_wp: add option to reset mission counters when setting waypoint

MAVProxy/modules/mavproxy_link.py
some of these MAV_TYPEs are not known in older bindings, e.g. MAV_TYPE_BATTERY.  Avoid fatal errors here when we're working with older bindings
```
MAV> Detected vehicle 1:1 on link 0
Exception in thread main_loop:
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.8.62-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 1129, in main_loop
File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.8.62-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 819, in process_master
File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-2.4.39-py2.7.egg/pymavlin …
```
=> mavproxy_link.py: correct behaviour with old bindings

MAVProxy/modules/mavproxy_console.py, MAVProxy/modules/mavproxy_link.py
unreadable on Window's concept of "green", so I swiped the RGB values from Linux
=>  mavproxy_link: use numeric code for green

MAVProxy/modules/mavproxy_misc.py
for use by the relative-alt and abs-alt variants
=> mavproxy_misc.py: factor out a _cmd_changealt

.gitmodules
Add my MAVCesium fork and expose it a bit better in MAVProxy.
With `mavproxy.py --cesium`, it will start the web server, which you can open at `http://0.0.0.0:5000/mavcesium/#`.
You can also still do `module load cesium`.
Currently, mavproxy does not connect properly when launched in this mode. It works best with the standalone mode, where you launch mavproxy, then launch mavcesium separately in another terminal. 
```bash
python3 cesium_web_server.py
```
I'll chase that down soon - it's likely a difference in default options because the websocket receives no data.
I'd like to propose merging this as-is with the known deficiency because it's still a large improvement.
Here's what you get:
Birds eye view of Kaga (default on open when you start SITL in Kaga)
Once you take off, the takeoff …
=> MAVCesium: Switch to newer fork

MAVProxy/modules/mavproxy_link.py
Add ability to add a websocket server in the MAVProxy menu. It's only added if wsproto is installed.
* https://github.com/ArduPilot/ardupilot/pull/28560
* https://github.com/ArduPilot/pymavlink/pull/967
[mavproxy_1481_websocket_server.webm](https://github.com/user-attachments/assets/02124a5e-273e-47b8-abe4-f94c087a359e)
* Give users the ability to change which port number. The current one matches webtools.
* Any tips on other places that open up a text box when you click?
=> Add Start Websocket Server to the MAVProxy console

MAVProxy/modules/mavproxy_link.py
Add a way to customize which port you use for the websocket server.
The default works with webtools.
[Screencast from 11-16-2024 06:18:48 PM.webm](https://github.com/user-attachments/assets/17d1cc5a-d502-446f-b3df-4f70ae57eabc)
https://github.com/ArduPilot/MAVProxy/pull/1481
=> Websocket start with custom port

MAVProxy/mavproxy.py
Makes mavproxy executable so that it's easier to spin up a debugger in VSCode.
```
cd MAVProxy/MAVProxy
./mavproxy.py -h
```
=> Make mavproxy executable directly

MAVProxy/modules/lib/wxhorizon_ui.py
fix 2D line set_data error in ui update loop
https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D.set_data
```
RuntimeError: x must be a sequence
File "/opt/homebrew/lib/python3.9/site-packages/MAVProxy/modules/lib/wxhorizon_ui.py", line 627, in on_timer
self.updateAltHistory()
File "/opt/homebrew/lib/python3.9/site-packages/MAVProxy/modules/lib/wxhorizon_ui.py", line 518, in updateAltHistory
self.altMarker.set_data([self.leftPos+(self.vertSize/10.0)+0.5,val])
File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/lines.py", line 665, in set_data
self.set_xdata(x)
File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/lines.py", line 1289, in set_xdata
raise RuntimeError('x must be a sequence') …
```
=> fix altMarker set_data error

.github/workflows/windows_build.yml, MAVProxy/MAVProxyWinLAN.bat, MAVProxy/MAVProxyWinUSB.bat, MAVProxy/modules/lib/grapher.py, MAVProxy/modules/lib/magfit.py, MAVProxy/modules/lib/param_help.py, MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py, MAVProxy/tools/MAVExplorer.bat, MAVProxy/tools/MAVExplorer.py, windows/MAVProxyWinBuild.bat, windows/mavproxy.spec
Fixed two issues with MAVExplorer graphs not working nicely:
- Changed to "TkAgg" backend on Windows, as the "wxAgg" backend wasn't displaying the chart values (lower right) correctly
- When saving graphs to file ("save" icon on graph window), made the _suggested_ filename safer by removing problematic characters (ie ``Sensors/GPS/GPS Accuracy`` to ``Sensors_GPS_GPS_Accuracy``)
=> Modules: grapher layout and file export fixed for Windows

MAVProxy/modules/mavproxy_param.py
Adds ability to toggle, set and clear bitmask parameters.
=> modules: add bitmask modifying to param module

MAVProxy/modules/mavproxy_console.py
Exceptions are easy reproduce - just `module unload wp`
=> Avoid exceptions when wp module is not loaded

MAVProxy/modules/mavproxy_param.py
Sanity check bitmask index when setting bitmask
=> modules: add sanity checking to bitmask index when setting bitmask parameter

MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py
Closes #1265
This can be implemented at a later date.
=> missionEditorFrame.py: Remove unimplemented AGL checkbox

MAVProxy/modules/mavproxy_mode.py
Adds tab completion of mode names when changing mode using the command `mode <MODE>`.
Also prettifies printing of available modes - this previously printed an array of  `dict_keys([..], ...)`
=> mavproxy_mode: Allow for mode names to be tab completed

MAVProxy/modules/mavproxy_param.py
Stop using pymavlink's mavparm.mavset method as its retry logic is synchronous, meaning MAVProxy stops processing in the main loop in the case there are link issues occuring
Creates an internal queue of parameters to send.  These are copied into a dictionary which is processed in mavproy_param's idle task.
Tested:
- can set values(!)
- good error message when invalid value supplied
- SITL and real board
- returned value matches sent value (and good message for mismatch)
- setting parameters when the autopilot goes away times out
- new-sets override old-sets
- retry logic works (SITL-only by ctrl-z'ing the simulation while attempting the set, fg'ing after 1 second has passed, inspecting `PARAM_VALUE` messages received)
```
ACRO> param set RC3_OPTION 43
ACRO> param fetch RC3_OPTION
ACRO> …
```
=> mavproxy_param: handle param set requests asynchronously

MAVProxy/modules/mavproxy_soar.py
Add an initial soaring module, which displays the location and estimated radius of the thermal from AP's thermal soaring estimator.  
Once we have a mavlink packet definition for the thermal estimator, we can move to that from NAMED_VALUE_FLOAT.
Enable the NVT for the EKF and run the soaring autotest without speedup.
Terminal 1:
```bash
./Tools/autotest/autotest.py build.Plane test.Plane.Soaring --map --speedup=1 --waf-configure-args "--define HAL_SOARING_NVF_EKF_ENABLED=1"
```
Terminal 2:
```bash
mavproxy.py --console --master tcp:127.0.0.1:5763 --map
module load soar
```
Once the vehicle hits the thermal southwest of home, it will show up on the map. You can see the estimator converge on the thermal.
=> mavproxy_soar: Add initial soaring display

MAVProxy/modules/lib/wxrc.py
Fixes graphical bug in RC and Servo GUI when the PWM value is > 2000
=> RC: Make RC GUI fit according to max received value

MAVProxy/modules/mavproxy_param.py
Fixes a change made in #1408 that passes in an incorrect keyword argument into set_parameter
=> mavproxy_param: fixes broken parameter setting

MAVProxy/modules/mavproxy_misc.py
we need new and interesting ways to torture our autopilots.
Understand a new command which asks the autopilot to enter its config error loop.  This can be useful for testing GCS behaviour while autopilot is in this state.
=> mavproxy_misc.py: add configerror_autopilot command

MAVProxy/modules/mavproxy_joystick/controls.py, docs/JOYSTICKS.md
Since there usually are no persistent switches on gamepads but just momentary switches, I added the "toggle" control to simulate persistent switches.
This allows to e.g. arm/disarm using a button.
`toggle` takes a list of values that are cycled through on every button press/release.
By using a list for `values`, not only on/off switches can be simulated but also multi-position or rotary switches as well.
=> mavproxy_joystick: add support for toggle buttons

MAVProxy/modules/mavproxy_link.py
``` shell
wsproto.utilities.LocalProtocolError: Event BytesMessage(data=bytearray(b'\xfd\x0f\x00\x00$\x01\x01\x82\x01\x00}\x04\x04\x98\xff\x00\x00\x07\xcb\x92\xb8G\x00\x00\xcc\xd5\xb4'), frame_finished=True, message_finished=True) cannot be sent during the handshake
```
fix raised error when sending mavlink packet during websocket handshake
=> mavproxy_link.py: fix websocket output sending mavlink pkt during hanshake

MAVProxy/modules/mavproxy_joystick/controls.py
fixes potential bug where channel value can change without a button state change just by reading Control.value repeatedly
=> mavproxy_joystick: only change channel value when button state actually changed

MAVProxy/modules/mavproxy_kmlread.py
allows loading kml that has incorrectly duplicated elements
=> kmlread: skip duplicate elements

MAVProxy/modules/lib/mission_item_protocol.py
rally clear
<<click on map>>
rally add
rally move 1
Before this patch that fails to pack the mission_item_int message as we are inserting floating point values into the item_int message x and y fields.
... same is true of waypoints
=> mission_item_protocol: fix 'move' on items we have not downloaded

MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
Use data available in the terrain module to overlay terrain contours on the map.
- Be able to overlay terrain contour lines on the existing slip map.
- Use existing terrain data sources to match information available on the FC.
- Initial step in adding support to mavproxy for configuring off-board terrain planning for planes. The idea is to replace the dependency on rviz and simplify the user workflow the example used here https://discuss.ardupilot.org/t/offboard-terrain-navigation-for-plane-with-ros-2-ap-dds/114418. 
Select the number of contour levels, grid resolution and grid extent using the map settings:
```bash
STABILIZE> map set
STABILIZE>           
brightness 1
circle_linewidth 1
contour_grid_extent 20000.0
contour_grid_spacing 30.0
contour_levels 20
font_size 0.5
loitercircle …
```
=> Add terrain contours to map

MAVProxy/modules/mavproxy_console.py
~Needs testing; I've creatively broken GPS, at least, with my refactoring.~  FIXED
=> Add support for FLIGHT_INFORMATION message

MAVProxy/modules/mavproxy_adsb.py
displayed alt is now difference from vehicle alt
=> adsb: improve display and add traffic warning

MAVProxy/modules/lib/mp_menu.py, MAVProxy/modules/mavproxy_map/__init__.py, MAVProxy/modules/mavproxy_mode.py
and remember previous frame and value
=> map: added dropdown selection of frame to FlyTo

MAVProxy/modules/lib/mp_checklist.py, MAVProxy/modules/mavproxy_checklist.py
added a scrollbar for long lists and added logging
=> checklist: scrollbar and logging

.github/workflows/windows_build.yml, MAVProxy/modules/lib/param_help.py, MAVProxy/modules/mavproxy_param.py, windows/MAVProxyWinBuild.bat
For the rover param downloads, there was an inconsistency between using "APMrover2.xml" and "Rover.xml", leading to the param module not using the correct xml file.
I've standardised on "APMrover2.xml"
=> Correct rover param download

setup.py
```
ryan@ryan-thinkpad:~/Dev/ardupilot_ws/src/MAVProxy$ python3 -m pip install -e .[cesium]
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/ryan/Dev/ardupilot_ws/src/MAVProxy
Preparing metadata (setup.py) ... done
Requirement already satisfied: pymavlink>=2.4.14 in /home/ryan/.local/lib/python3.10/site-packages (from MAVProxy==1.8.71) (2.4.42)
Requirement already satisfied: pyserial>=3.0 in /usr/lib/python3/dist-packages (from MAVProxy==1.8.71) (3.5)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from MAVProxy==1.8.71) (1.21.5)
Requirement already satisfied: pynmeagps in /home/ryan/.local/lib/python3.10/site-packages (from MAVProxy==1.8.71) (1.0.43)
Requirement already satisfied: tornado in …
```
=> Add cesium extras

MAVProxy/modules/mavproxy_map/mp_tile.py
For for #1582. Turns out the method of getting the map icon folder was incorrect.
=> Map: Use correct file path for icons

.github/workflows/windows_build.yml, MAVProxy/modules/mavproxy_chat/chat_voice_to_text.py, windows/MAVProxyWinBuild.bat
Installing the third-party ___Whole Architecture Verification___ module https://pypi.org/project/Wave is [breaking our builds](https://github.com/ArduPilot/MAVProxy/actions/workflows/windows_build.yml).
The Python Standard Library module  [`wave`](https://docs.python.org/3/library/wave.html) has an API that corresponds to:
https://github.com/ArduPilot/MAVProxy/blob/a45549f9bcb09603be1507c260de2bafe516212a/MAVProxy/modules/mavproxy_chat/chat_voice_to_text.py#L72-L78
Therefore, we should stop doing `pip install wave` and instead use the Standard Library.
The docs at https://ardupilot.org/mavproxy/docs/modules/chat.html#prerequisites must also be modified.
* ArduPilot/ardupilot_wiki#6947
@rmackay9 Your review, please.
=> `wave` is a Python Standard Library module

MAVProxy/mavproxy.py, MAVProxy/modules/lib/grapher.py
This would allow MAVProxy to see messages in other inclusions in `all.xml` - so including the ones in `storm32.xml` for example.
I've run this for a while locally and it seems to run just fine.
=> MAVProxy: default to using the 'all' dialect

MAVProxy/modules/lib/optparse_gui/__init__.py
flake8 rule F821 -- Undefined names have the potential to raise NameError at runtime.
`unicode()` appears on line 90.
=> optparse_gui: Keyword 'unicode' was removed in Python 3

MAVProxy/modules/lib/mp_util.py
There has been new sensors added that are unable to be decoded with devid in mavproxy and MAVExplorer. This adds those new sensors.
=> mp_util: Update decoders in decode_devid

MAVProxy/modules/lib/camera_projection.py
flake8 rule F821 -- Undefined names have the potential to raise NameError at runtime.
`import json` needed for lines 64 and 106.
~`self` needed for line 87.~
Line 87 mistakenly used `self`.
=> camera_projection.py: Fix undefined names 'json' and 'self'

MAVProxy/modules/mavproxy_map/mp_slipmap.py
Restore missing import in `map` module required for macOS.
=> mavproxy_map: import wx_processguard required for macOS
