ArduPilot/MAVProxy

MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_map/mp_slipmap.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py

Closing the map window unloads the map module
Unloading the map module closes the map window

map: map unloading fixes

---

flightModes.html
index.html
mavcustmod.html
mavdevenv.html
modules.html
nsh.html
quickstart.html
starting.html
terrain.html

Mostly including new useful modules.

Another big documentation update

---

windows/MAVProxy.pyproj
windows/MAVProxy.sln

Added Visual Studio project files to assist Windows-based developers

Windows - Visual studio project files

---

docs/source/getting_started/download_and_installation.rst

Fixing this issue -https://github.com/Dronecode/MAVProxy/issues/286
I also tested in a clean ubuntu 14.04 virtual machine and found I needed python-dev as well.
Thanks, Grant.

Docs: Added python-dev to installation

---

MAVProxy/modules/lib/live_graph_ui.py

Live Graph UI: nicer scaling and formatting for y-axis

---

MAVProxy/modules/mavproxy_param.py

Param Module: Correct help message

---

MAVProxy/modules/mavproxy_terrain.py

Terrain module: Correct help message

---

MAVProxy/modules/lib/rline.py

rline: tab-complete the empty string

---

MAVProxy/mavproxy.py

Also print script names as we execute them

Run scripts from aircraft directories

---

.gitignore

This generated file should be ignored

Windows installer: Ignore generated file

---

windows/MAVProxyWinBuild.bat

If the user has a local copy of pymavlink chances are that he/she wants to use it :)

Windows installer: Rebuild and use pymavlink from sources if available

---

MAVProxy/modules/lib/wavefront.py
MAVProxy/modules/mavproxy_magical/magical_ui.py

Hello guys,
This PR addresses #374. I decided to keep the caching mechanism implemented but disabled, in case we need it in the future. If someone more experienced than me in 3D rendering can tell we will never need it, I'll be happy to wipe it out from the code :-)

magical: don't use cache

---

MAVProxy/modules/mavproxy_magical/__init__.py
MAVProxy/modules/mavproxy_magical/magical_ui.py
MAVProxy/modules/mavproxy_magical/wxgeodesicgrid.py

And fix problem of finding resources when installed as a python egg.
This fixes https://github.com/ArduPilot/MAVProxy/issues/373.

magical: use pkg_resources when possible

---

MAVProxy/modules/mavproxy_smartcamera/__init__.py
MAVProxy/modules/mavproxy_smartcamera/sc_ExifWriter.py
MAVProxy/modules/mavproxy_smartcamera/sc_SonyQX1.py

Several fixes, added image download function, and added geotag writer to exif. The module is now capable of downloading all the pictures taken during a session and adding the geotag to the exif data while downloading the image.

Smart camera update

---

MAVProxy/MAVProxyWinLAN.bat
windows/Startup Examples/MAVProxyLogput.bat
windows/Startup Examples/MAVProxyMultiOutput.bat
windows/mavproxy.iss

Ensure that MAVProxy is removed from %PATH% on uninstallation. Also provided some example batch files showing startup options

Windows: remove path on uninstallation. Also some example startup

---

MAVProxy/mavproxy.py

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

mavproxy: Move prints to python3 compatibility

---

MAVProxy/modules/mavproxy_map/srtm.py

Fixed issues where there is no maps cache and the user is offline

Maps: Fixed offline handling when there are no cached files

---

MAVProxy/modules/mavproxy_fence.py

Like we do for the other sensors

mavproxy_fence: show FEN in black when not present

---

MAVProxy/modules/mavproxy_map/mp_tile.py

it was inop due to unsupported version.

Map: fixed Google Sat map

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/ANUGA/geo_reference.py
MAVProxy/modules/lib/ANUGA/redfearn.py
MAVProxy/modules/lib/live_graph.py
MAVProxy/modules/lib/live_graph_ui.py
MAVProxy/modules/lib/mp_checklist.py
MAVProxy/modules/lib/mp_image.py
MAVProxy/modules/lib/mp_menu.py
MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/lib/mp_widgets.py
MAVProxy/modules/lib/textconsole.py
MAVProxy/modules/lib/wx_loader.py
MAVProxy/modules/lib/wx_processguard.py
MAVProxy/modules/lib/wxconsole.py
MAVProxy/modules/lib/wxconsole_ui.py
MAVProxy/modules/lib/wxgrapheditor.py
MAVProxy/modules/lib/wxhorizon.py
MAVProxy/modules/lib/wxhorizon_ui.py
MAVProxy/modules/lib/wxsettings.py
MAVProxy/modules/lib/wxsettings_ui.py
MAVProxy/modules/mavproxy_link.py
MAVProxy/modules/mavproxy_map/mp_slipmap.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
MAVProxy/modules/mavproxy_map/mp_tile.py
MAVProxy/modules/mavproxy_map/srtm.py
MAVProxy/modules/mavproxy_misseditor/__init__.py
MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py
MAVProxy/modules/mavproxy_misseditor/mission_editor.py

Most of the basics seem to work
Current issues:

added python3 support

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_link.py

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

Enable mavproxy to watch multiple messages

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/mp_menu.py
MAVProxy/modules/lib/mp_module.py
MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_link.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/modules/mavproxy_rally.py
MAVProxy/modules/mavproxy_wp.py
setup.py

add concept of modules that support multiple vehicles. If they don't
then they only get messages for primary system ID
depends on: https://github.com/ArduPilot/pymavlink/pull/251

support multiple system ID links

---

MAVProxy/modules/mavproxy_checklist.py

Undefined name: import math for line 79

---

MAVProxy/modules/lib/MacOS/backend_agg.py

Tested working on macos Mojave

live_graph: fix live graph on macos

---

README.md

Added Appveyor badge so Windows build status can be easily seen. Also moved Gitter badge up next to it.

CI - Added Appveyor Badge

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_help.py
MAVProxy/modules/mavproxy_map/srtm.py
README.md
appveyor.yml
windows/MAVProxyWinBuild.bat

A bunch of Python 3 fixes. Also changing the Windows build over to Python 3.

Python 3 Fixes

---

MAVProxy/modules/lib/graph_ui.py
MAVProxy/modules/lib/grapher.py
MAVProxy/tools/MAVExplorer.py

`set title FooBar`
... or if you select something from a menu item it takes the canned name.

MAVExplorer: add option to add title to graph

---

MAVProxy/modules/mavproxy_restserver.py

Add rest server:
`module load restserver`
`restserver start`
`restserver stop`
`restserver address 127.0.0.1:3333`
Allow information access via simple rest api:
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

Module: Add server module

---

MAVProxy/mavproxy.py

Only on systems with DBUS available.

mavproxy.py: inhibit screensaver while vehicle is armed

---

MAVProxy/modules/lib/rline.py

Primarily just reordering things so we check for valid expression last.
Also removes some pointless try blocks

rline.py: correct tab completion function for MAG vs MAG2

---

MAVProxy/mavproxy.py

```
RTL> status --verbose HEARTBEAT HWSTATUS
RTL> 2019-05-11 22:43:52.17: HEARTBEAT (link=None) (signed=False) (seq=156) (src=1/1)
type: 1 (MAV_TYPE_FIXED_WING)
autopilot: 3 (MAV_AUTOPILOT_ARDUPILOTMEGA)
base_mode: 89
MAV_MODE_FLAG_CUSTOM_MODE_ENABLED
! MAV_MODE_FLAG_TEST_ENABLED
! MAV_MODE_FLAG_AUTO_ENABLED
MAV_MODE_FLAG_GUIDED_ENABLED
MAV_MODE_FLAG_STABILIZE_ENABLED
! MAV_MODE_FLAG_HIL_ENABLED
MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
! MAV_MODE_FLAG_SAFETY_ARMED
custom_mode: 11
system_status: 5 (MAV_STATE_CRITICAL)
mavlink_version: 3
2019-05-11 22:43:52.53: HWSTATUS (link=None) (signed=False) (seq=200) (src=1/1)
Vcc: 4.98V
I2Cerr: 0
```
Requires https://github.com/ArduPilot/pymavlink/pull/316

mavproxy.py: add --verbose option to status

---

MAVProxy/modules/mavproxy_adsb.py

add emitter_type==255 check for Object Avoidance Database values to draw on the map. Normal ADSB packets with emitter_types in the normal <20 range are not effected.
This type of adsb object has no icon, only a "threat_radius" that is very small. There's a video example of this in PR https://github.com/ArduPilot/ardupilot/pull/11671

OA DB via ADSB: show dynamic radius without icon for OA database items

---

MAVProxy/modules/mavproxy_rc.py

Also parameterise the number of channels....

mavproxy_rc: send through 18 channels in RC_CHANNELS_OVERRIDE

---

MAVProxy/modules/mavproxy_fakegps.py

fakegps: added module to fake GPS input

---

MAVProxy/modules/mavproxy_param.py
MAVProxy/modules/mavproxy_paramedit/__init__.py
MAVProxy/modules/mavproxy_paramedit/param_editor.py
MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py

Parameter menu added to the console
@tridge  @peterbarker  Please let me know if anything else needs to be added to the menu.

Added Parameter menu to console

---

MAVProxy/modules/mavproxy_fieldcheck/__init__.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_misseditor/mission_editor.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/modules/mavproxy_rally.py

Using these methods will let us abstract things within mavproxy_rally

Stop using rallyloader member from rally module

---

MAVProxy/modules/mavproxy_paramedit/checklisteditor.py
MAVProxy/modules/mavproxy_paramedit/param_editor.py
MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
MAVProxy/modules/mavproxy_paramedit/ph_event.py

Highlight current flight mode. Resolved bugs on setting parameters and redraw based on search key.

FLIGHT mode

---

MAVProxy/modules/mavproxy_wp.py

```
MANUAL> wp split 4
.
.
MANUAL> wp split 3
```

mavproxy_wp: add split command for splitting MAV_CMD_NAV_WAYPOINT in two

---

MAVProxy/modules/mavproxy_movinghome.py

This module will update the home position of a vehicle with the position of the GCS.
A NMEA device, connected to the MAVProxy, will provide the position of the GCS, this module will then update the vehicle home position every x seconds if the position is changed by >x meters.
Very useful for operating from a ship.  - in case of connection loss, home is the latest known position of the ship.

Created module movinghome

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/mp_menu.py
MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_rally.py

... also remove from public modules list on unload

Correct menu addition and removal when modules loaded/unloaded

---

MAVProxy/tools/MAVExplorer.py

useful for seeing changes in flight

MAVExplorer: added paramchange command

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_cmdlong.py
MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_genobstacles.py
MAVProxy/modules/mavproxy_gimbal.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
MAVProxy/modules/mavproxy_misseditor/__init__.py
MAVProxy/modules/mavproxy_mode.py
MAVProxy/modules/mavproxy_rally.py
MAVProxy/modules/mavproxy_terrain.py
MAVProxy/modules/mavproxy_wp.py

Also fixes a few places where we weren't checking for None.
Also adds a command so you can synthesise a click location, e.g.
```
STABILIZE> click -35.3632622 149.1652377
STABILIZE> click GLOBAL_POSITION_INT.lat/1e7 GLOBAL_POSITION_INT.lon/1e7
```
Also draws your click location on the map.

Move click location into mpstate

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_wp.py

this fixes accuracy of wp upload

wp: fixed wp upload to use MISSION_ITEM_INT

---

MAVProxy/modules/mavproxy_signing.py

Should fix #710 
This is from August.... my bad.

mavproxy_signing: Python3 fix

---

MAVProxy/modules/mavproxy_log.py

@peterbarker 
Your suggestion is in place, took me some time to figure out how to access size :)
it is clearly the better option.

log: skip existing files only if size matches, improve help

---

MAVProxy/modules/mavproxy_ftp.py

Under Python3:
MANUAL> Getting terrain/FOO.DAT as -
b'FREDDLES!\n'
Flight battery 100 percent
Under Python2:
MANUAL> Getting terrain/FOO.DAT as -
FREDDLES!
MANUAL>

mavproxy_ftp: make it work under Python3

---

MAVProxy/modules/lib/grapher.py
MAVProxy/modules/mavproxy_map/mp_slipmap.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
MAVProxy/tools/MAVExplorer.py
MAVProxy/tools/mavflightview.py

As you zoom or pan graphs the points on the map that cover the x timeline currently in range are shown
This makes it easy to see the flight path for a portion of the log

MAVExplorer: added sync of map display to time axis zooming

---

MAVProxy/modules/mavproxy_cmdlong.py

Here is a patch to fix a security issue due to the use of `eval`.
As I don't know how to test it properly, I let you guys check everything is working well (I did some basic checks and things seem ok).
Let me know if there is some changes to do.

#753 Security issue with cmd long

---

MAVProxy/modules/mavproxy_joystick/joysticks/great-planes.Interlink-X.yaml

This is a file submitted for the addition of a joystick configuration for the great planes interlink X controller. This was originally for a issue # 620 under my different profile.

Added joystick config file for GP Interlink X

---

MAVProxy/tools/mavflightview.py

Handy when trying to look at values-above-thresholds and there's lots of datapoints in play.

Allow colour expression to return none so point not plotted

---

MAVProxy/modules/mavproxy_param.py

Only checks that values are in enumeration initially.
Other checks might be unknown-bitmask-bits set, values within range, ...

mavproxy_param: add a check command

---

index.html

This will redirect anyone with the old http://ardupilot.github.io/MAVProxy link to the ArduPilot wiki

Add auto-redirect to new doco

---

MAVProxy/modules/mavproxy_help.py

Fix issue where the help module would produce errors if there was no Internet connection on startup.

Modules: fix help module errors when no Internet

---

MAVProxy/tools/MAVExplorer.py
MAVProxy/tools/mavflightview.py

See https://github.com/ArduPilot/pymavlink/pull/444

Support conditions expressions

---

MAVProxy/modules/lib/wxhorizon_ui.py

fixes sky / ground polygon switching at +-90° roll

horizon: fix roll beyond +-90 deg

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/win_layout.py
MAVProxy/modules/mavproxy_help.py
MAVProxy/tools/MAVExplorer.py

This PR consolidates all access to the ``.mavproxy`` folder to be through ``mp_util.dot_mavproxy()``
Have tested in python2 and 3 in Linux and Windows.

Util: Consolidate .mavproxy folder access to mp_util.dot_mavproxy()

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_param.py

Takes advantage of https://github.com/ArduPilot/ardupilot/pull/15335 (once that is merged....)

Download compresses parameter files from autotest server

---

MAVProxy/modules/mavproxy_DGPS.py

I do not have hardware to test this on.
Tested by throwing random data at the port and checking for obvious Python errors.  This testing was done on both Python2 and Python3.

mavproxy_DGPS: Python3 fixes

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/rline.py
MAVProxy/modules/mavproxy_link.py

this supports tab completion and array syntax for instance type
messages in both mavlink and binary log files
Requires
https://github.com/ArduPilot/mavlink/pull/150 and
https://github.com/ArduPilot/pymavlink/pull/459

support instance fields and array syntax

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_link.py

we need to compare millisec numbers between only vehicles using the same sysid

fixed graphing with multiple vehicles

---

MAVProxy/mavproxy.py

If the remote mavproxy is connected on several links then try to fwd
msgs to the best link using the target system ID of the incoming msg

try to fwd incoming messages to the best link

---

MAVProxy/modules/mavproxy_useralerts.py

The URL for User Alerts was updated to be more sensible.

Modules: Update URL for User Alerts

---

MAVProxy/modules/lib/magfit.py
MAVProxy/modules/lib/msgstats.py
MAVProxy/tools/MAVExplorer.py

added Tools menu

---

.azure/azure-pipelines.yml

Fix a pickling issue affecting MAVExplorer > Tools on windows
Fixes #845

Update azure pipeline to use Python 3.9

---

MAVProxy/modules/mavproxy_proximity.py

We make the assumption here that we only get 65535 back when we're out
of readings, not in the middle of all of the other readings.

mavproxy_proximity: make corrections to FOV

---

MAVProxy/modules/lib/mp_util.py

py2 gzip doesn't have decompress()

mp_util: fixed param download in py2

---

MAVProxy/modules/mavproxy_console.py

If proximity sensor is ever seen as present, displays a `PRX` sensor status bit.
if prearm sensor bit is ever seen as present, adds a `PRE` sensor status bit.
Announces prearm state changing state - if speech is enabled that means you get "pre arm good" and "pre arm fail" spoken at you.

mavproxy_console: support PRE and PRX SYS_STATUS bits

---

MAVProxy/modules/lib/grapher.py

very useful when right axis and left axis on different scales

grapher: added double click to rescale Y axes to current data

---

MAVProxy/modules/mavproxy_calibration.py

see https://github.com/ArduPilot/ardupilot/pull/16591

calibration: added forcecal command

---

MAVProxy/modules/mavproxy_map/mp_slipmap.py

This PR is to fix issue #874 that prevents the mavflightview.py or MAVExplorer > Display > Map from working on macOS.
The problem arises because the parent process that creates the MPSlipMap, which is called in the function `mavflightview_show` in `mavflightview.py`,  goes out of scope before the child process containing the wxPython map has been fully started. See this report [Multiprocessing spawn/forkserver fails to pass Queues](https://bugs.python.org/issue28965) for a discussion. 
The proposed solution adds a multiprocessing Event to MPSlipMap which is set by the child task when the map application and frame are ready to enter their main loop. The MPSlipMap initialise function waits for this event before returning (with a timeout of 2s).
Adding some debug output to …

mavflightview: fix for #874 on macOS

---

MAVProxy/modules/mavproxy_gimbal.py

When used with the simulator like gazebo it's easy to have this option on command line as well.

Add the option to set gimbal roi from the commandline

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/wx_addlink.py
MAVProxy/modules/mavproxy_link.py
MAVProxy/modules/mavproxy_mode.py

This PR adds a GUI for adding links by modifying the link module's menu to include a custom dialog.
Tested in Ubuntu20 and Windows10.

GUI for adding links

---

MAVProxy/mavproxy.py

As it was the code produced vast amounts of information - all of it
useless as the last line was lost.
Now it produces vast amounts of information - but now useful as you get
enough to diagnose the problem!

mavproxy.py: improve stack trace production

---

MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_ftp.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/modules/mavproxy_wp.py

matching ardupilot PR: https://github.com/ArduPilot/ardupilot/pull/17102

wp: added ftp download option

---

MAVProxy/modules/lib/magfit.py

magfit: fix attitude for trim

---

MAVProxy/modules/mavproxy_map/__init__.py

map: fixed vehicle default icon

---

MAVProxy/tools/mavflightview.py

resolves
No colormap for mav_type=11

mavflightview.py: use Rover colourmap for MAV_TYPE_SURFACE_BOAT

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_followtest.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_tile.py

allows for map display across 180 degree longitude boundary

cope with longitude wrap

---

MAVProxy/modules/mavproxy_map/__init__.py

This one is sometimes under autonomous control

mavproxy_map: add ZIGZAG to NAV_CONTROLLER_OUTPUT modes

---

MAVProxy/modules/lib/grapher.py

this fixes the double display of points with multiple instances, for
example:
GPS[0].Spd GPS[1].Spd
it should display the GPS[1].Spd twice

grapher: fixed graph of multiple instances

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
MAVProxy/modules/mavproxy_map/mp_tile.py
MAVProxy/tools/mavflightview.py

map: improved display at larger zooms

---

MAVProxy/tools/graphs/mavgraphs.xml

Copter limits according to this calculation

mavgraphs.xml: add Circular Angle graph for vehicle attitude

---

MAVProxy/modules/mavproxy_map/data/image_vector_files/heli_icon.svg

Follow on from #917.  Adding the .svg file for the heli icon.

Map: Add heli icon *.svg

---

MAVProxy/modules/mavproxy_map/__init__.py

Map: Add deca and dodeca mav type to copter icon

---

MAVProxy/modules/mavproxy_map/srtm.py

see
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

SRTM: avoid SSL certification issue with http vs https option

---

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py

map: added zoom menu items

---

MAVProxy/tools/MAVExplorer.py

MAVExplorer: added file command

---

MAVProxy/modules/mavproxy_misc.py

allows stop/restart of lua scripts

misc: added scripting cmd

---

MAVProxy/modules/mavproxy_asterix.py

It's been a while since we last used this module, fixed a few Python3 issues.

Asterix: Python 3 compatibility

---

MAVProxy/modules/mavproxy_ais.py

This PR adds support for the AIS_VESSEL message. It displays AIS vessels on the map. Requires https://github.com/ArduPilot/ardupilot/pull/13839 to send messages.

Add AIS module

---

MAVProxy/tools/mavflightview.py

Add plotting of GUID log points when they are locations.

mavflightview: add GUID Plotting

---

MAVProxy/modules/mavproxy_osd.py

command does not do anything and causes display issues for the OSD parm-show command for some reason

Delete "set" command from OSD module

---

MAVProxy/modules/mavproxy_console.py

unload console module after close window

mavproxy_console:unload console module after close window

---

MAVProxy/modules/mavproxy_firmware.py

```
RTL> fw flash platform=CubeBlack frame=Rover latest=1 format=apj minor=2 major=4
RTL> fw: URL: https://firmware.ardupilot.org/Rover/latest/CubeBlack/ardurover.apj
Waiting for download to compliete...
Downloading https://firmware.ardupilot.org/Rover/latest/CubeBlack/ardurover.apj as ardurover.apj
Waiting for download to compliete...
Waiting for download to compliete...
Loaded firmware for 9,0, size: 1500288 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
Attempting reboot on /dev/serial/by-id/usb-Hex_ProfiCNC_CubeBlack_270036000B51353430373938-if00 with baudrate=57600...
If the board does not respond, unplug and re-plug the USB connector.
Could not get external flash size, assuming 0
Found board 9,0 bootloader …
```

Add support for flashing firmware from manifest.json or filepath

---

MAVProxy/modules/mavproxy_messagerate.py

Implements MAV_CMD_SET_MESSAGE_INTERVAL and MAV_CMD_GET_MESSAGE_INTERVAL for access to individual message rates.
messagerate set [MSG_NAME] [period_us]
messagerate get [MSG_NAME]

Module-messagerate : set and get message stream rates

---

MAVProxy/tools/mavflightview.py

faulthandler have no register attribute in windows, fixed that startup issue

mavlfightview: fixed faulthandler have no register in windows

---

MAVProxy/modules/lib/param_help.py

Before:
```
param help ATC_ACCEL_MAX
ACRO> Please run 'param download' first (vehicle_name=APMrover2)
```
After:
```
MANUAL> param help ATC_ACCEL_MAX
MANUAL> ATC_ACCEL_MAX: Speed control acceleration (and deceleration) maximum in m/s/s
Speed control acceleration (and deceleration) maximum in m/s/s.  0 to disable acceleration limiting
Range : 0.0 10.0
Increment : 0.1
Units : m/s/s
UnitText : meters per square second
```

paramhelp: check for presence of APMrover2.xml

---

MAVProxy/modules/mavproxy_misc.py

STABILIZE> setorigin -35.3621474 149.1651746 600
STABILIZE> Setting origin to:  -35.3621474 149.1651746 600.0

mavproxy_misc: cast fields to int in set_gps_global_origin_send

---

MAVProxy/modules/lib/live_graph_ui.py

fixed wx.Timer error

---

MAVProxy/modules/mavproxy_joystick/joysticks/FeiYing.yml

A famous one used by hobbyists
I've tested it myself for a friend and confirmed working successfully

Add FeiYing Model KMODEL Simulator joystick

---

MAVProxy/modules/mavproxy_battery.py

and allow display of multiple batteries

battery: use BATTERY_STATUS

---

.github/workflows/windows_build.yml
README.md

Fixes for the upgraded windows server 2022

CI: Add Inno setup

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_link.py
MAVProxy/modules/mavproxy_map/__init__.py

This adds support for https://mavlink.io/en/services/high_latency.html, plus a few relevant bugfixes.
Requires pymavlink master.

Add High Latency Protocol support

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_map/__init__.py

useful in swarms to make vehicles distinct

map: allow for override of vehicle type

---

MAVProxy/modules/mavproxy_cmdlong.py

This updates the attitude command so you send the typemask and angular velocities.

mavproxy_cmdlong: attitude add angular rates & mask

---

MAVProxy/tools/graphs/mavgraphs.xml
MAVProxy/tools/graphs/mavgraphs2.xml

graph update

---

MAVProxy/modules/mavproxy_map/mp_tile.py

fix tile files download with ssl error in python3

fix map stop loading error

---

MAVProxy/modules/mavproxy_mqtt.py

added a module to publish mavlink messages to mqtt

added mqtt module

---

.flake8

flake8: add .flake8

---

MAVProxy/modules/lib/ntrip.py
MAVProxy/modules/mavproxy_arm.py

this prevents blocking main thread when there is no internet link

ntrip: make connection non-blocking

---

MAVProxy/modules/mavproxy_log.py

This adds to option to download logs *from* a certain log.
for example:
```
...
Log 307  numLogs 343 lastLog 343 size 1032192 Thu Sep 16 14:32:58 2021
Log 308  numLogs 343 lastLog 343 size 896512 Fri Sep 17 09:45:20 2021
Log 309  numLogs 343 lastLog 343 size 951808 Fri Sep 17 09:53:50 2021
Log 310  numLogs 343 lastLog 343 size 833536 Fri Sep 17 09:58:18 2021
Log 311  numLogs 343 lastLog 343 size 1458176 Fri Sep 17 10:26:32 2021
Log 312  numLogs 343 lastLog 343 size 4370432 Fri Sep 17 13:36:34 2021
Log 313  numLogs 343 lastLog 343 size 2916352 Fri Sep 17 13:38:50 2021
Log 314  numLogs 343 lastLog 343 size 1601536 Fri Sep 17 13:40:04 2021
Log 315  numLogs 343 lastLog 343 size 1056768 Fri Sep 17 13:40:52 2021
Log 316  numLogs 343 lastLog 343 size 1269760 Fri Sep 17 13:41:50 2021
Log 317 …
```

Log Module: add option to"download from <lognumber>"

---

MAVProxy/modules/mavproxy_wp.py

and make draw add to end of mission. This allows for more complex
missions with the menu

wp: added takeoff, landing and DO_LAND_START menu items

---

MAVProxy/modules/mavproxy_misseditor/mission_editor.py

changes on map are immediately reflected in the editor

misseditor: sync from WP module to editor

---

MAVProxy/modules/mavproxy_misseditor/missionEditorFrame.py
MAVProxy/modules/mavproxy_misseditor/mission_editor.py
MAVProxy/modules/mavproxy_wp.py

and fixed loop index with takeoff

wp: auto get home position

---

MAVProxy/modules/lib/grapher.py
MAVProxy/tools/MAVExplorer.py

allows ubuntu 22.04 with latest matplotlib nightly to work

MAVExplorer: fixes for py3.10 and latest matplotlib

---

MAVProxy/tools/graphs/mavgraphs.xml

From context, with the traditional lack of `<description>`....

graphs: add weights graph for GSF

---

MAVProxy/tools/mavflightview.py

these can sometimes be distracting

mavflightview.py: add option to not show the waypoints

---

MAVProxy/modules/mavproxy_wp.py

This simply moves methods towards the end of the file which will  become part of "class WPModule(MissionItemProtocolModule)"

mavproxy_wp: rearrange functions to allow subclasses

---

MAVProxy/modules/mavproxy_silvus.py

this gives nmea output to silvus radios, and logs key fields into the local mavlink log for analysis of radio performance interleaved with MAVLink data

Silvus: added radio status module

---

MAVProxy/mavproxy.py

allows for forwarding from downstream links only when disarmed,
allowing then to connect and get parameters but not impact on flight

added mavfwd_disarmed settings

---

MAVProxy/modules/lib/grapher.py
MAVProxy/modules/lib/rline.py
MAVProxy/modules/mavproxy_graph.py
MAVProxy/modules/mavproxy_silvus.py

needs this pymavlink PR for tlogs: https://github.com/ArduPilot/pymavlink/pull/690

Improved tab completion and graphing of instance fields 

---

MAVProxy/modules/lib/grapher.py

this prevents graphs like: BAT[1].Curr showing duplicate values from BAT[0]

fixed duplicate graph point display

---

MAVProxy/modules/mavproxy_map/mp_elevation.py

elevation: accept the old "srtm" name as SRTM3

---

MAVProxy/modules/lib/mp_menu.py

and use unique IDs from wx.NewId()
tested on ubuntu 22.04 and windows 10 both with python3
tested with py2 on ubuntu 18.04

mp_menu: prevent menu IDs crossing process boundaries

---

MAVProxy/modules/mavproxy_map/mp_elevation.py

This allows a user to point to special places they may be storing their data

map: mp_elevation: take and pass cachedir through in ElevationModel init

---

MAVProxy/modules/mavproxy_OpenDroneID.py
MAVProxy/modules/mavproxy_fakegps.py

this is a much more efficient way of updating operator position

added support for OPEN_DRONE_ID_SYSTEM_UPDATE message

---

MAVProxy/modules/mavproxy_SecureCommand.py

for changing params on RemoteID modules securely

SecureCommand: added setconfig

---

MAVProxy/tools/MAVExplorer.py

needs https://github.com/ArduPilot/pymavlink/pull/737

MAVExplorer: added "param diff" for 4.3.x logs

---

MAVProxy/modules/lib/param_ftp.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/tools/MAVExplorer.py

supports both showing parameters and param diff to defaults if the ftp has default values from 4.3 firmware

support ftp decode of parameters from tlogs

---

MAVProxy/modules/mavproxy_param.py

and use internal defaults buffer for defaults for param diff

param: avoid saving defaults.parm when no --aircraft option

---

MAVProxy/modules/mavproxy_wp.py

allows for use of param5/param6

wp: use is_location for scaling of lat/lon

---

MAVProxy/modules/mavproxy_ntrip.py

drop a percentage of fragments

ntrip: add frag_drop_pct

---

MAVProxy/modules/mavproxy_param.py

taking advantage of having proper defaults in mavftp

added param savechanged and param revert

---

MAVProxy/tools/graphs/mavgraphs.xml

graphs: added new FF graphs

---

MAVProxy/modules/mavproxy_map/mp_tile.py

prevents annoying new msg from opencv

map: check file exists before imread

---

MAVProxy/tools/graphs/ekf3Graphs.xml
MAVProxy/tools/graphs/mavgraphs.xml
MAVProxy/tools/graphs/mavgraphs2.xml

have not done Copter yet, but EKF,Plane, and QuadPlane

Update and organize provided graphs

---

MAVProxy/tools/MAVExplorer.py
MAVProxy/tools/graphs/mavgraphs.xml

useful for extracting parameters from a log

added param save and param savechanged

---

MAVProxy/tools/graphs/mavgraphs2.xml

Adds a few useful graphs I've been using with ArduRover.

MAVExplorer: Add Rover graphs

---

MAVProxy/modules/mavproxy_console.py

HWSTATUS no longer sent by default

console: fixed Vcc display

---

MAVProxy/modules/lib/grapher.py

this could lead to very high CPU load

grapher: prevent creation of duplicate xlim timer

---

MAVProxy/modules/mavproxy_map/mp_tile.py

Updated Norwegian maps. Added a basemap with topographic coverage of Svalbard.

Maps, added Svalbard

---

MAVProxy/modules/mavproxy_ftp.py

stop us spewing lots of warnings when someone else is doing a transfer

mavproxy_ftp: ignore FTP packets not targetted at me

---

MAVProxy/modules/mavproxy_speech.py

speech: added support for "@" prefix for speech output

---

MAVProxy/tools/MAVExplorer.py

needs the header to be loadable
needs some extra tabs for 0,0 lat long case to prevent columns with no space between

MAVExplorer: add mission file save and help

---

MAVProxy/modules/mavproxy_console.py

Only ArduPilot uses these fields this way
... Gremsy uses these fields for something else.

mavproxy_console: filter SYS_STATUS messages before warning of internal errors

---

MAVProxy/modules/mavproxy_link.py

prior to this PR MAVProxy only locked onto a system ID.
This leads to the situation that if you send a command you send it to all components of the vehicle.  This is probably not desired behaviour - by default you should probably only target the primary "autopilot" the vehicle.  An example of where this could be bad is MAV_CMD_DO_SET_MODE - it's entirely reasonable for a component to have its own set of custom modes, and if it processes MAVProxy's DO_SET_MODE intended for the autopilot may have unintended consequences
This PR changes things so we set both system ID and component ID when locking onto the vehicle based off heartbeat, so commands will be targetted at e.g. 1/1 rather than 1/0

mavproxy_link: MAVProxy locks onto both sysid and compid based on heartbeat

---

MAVProxy/modules/mavproxy_speech.py

this should avoid lockups caused by speech backends

speech: move speech to a subprocess

---

MAVProxy/modules/mavproxy_console.py

mavproxy_console: extract component name from GIMBAL_DEVICE_INFORMATION

---

.github/workflows/windows_build.yml
MAVProxy/modules/lib/grapher.py

maybe using plotlib timer instead of threading timer will help

grapher: attempt to fix windows close graph error

---

MAVProxy/mavproxy.py

otherwise we break old branch CI in ArduPilot

cope with older pymavlink versions

---

MAVProxy/modules/lib/graph_ui.py
MAVProxy/modules/lib/grapher.py
MAVProxy/tools/MAVExplorer.py

this allows for faster graphs by setting maximum message rate with "set max_rate N" in Hz

grapher: added max_rate setting

---

MAVProxy/modules/mavproxy_map/__init__.py

map: support setting external position estimate

---

MAVProxy/modules/mavproxy_console.py

display a "" initially to lock in location

console: give consistent ordering of user added items

---

MAVProxy/mavproxy.py
MAVProxy/modules/lib/mp_checklist.py
MAVProxy/modules/mavproxy_checklist.py
MAVProxy/modules/mavproxy_console.py
MAVProxy/modules/mavproxy_map/__init__.py

this allows for easy customisation of checklists

checklist: allow loading from checklist.txt in aircraft directory

---

MAVProxy/modules/lib/mp_menu.py
MAVProxy/modules/lib/wxconsole_ui.py
MAVProxy/modules/mavproxy_console.py

for example:
```
console menu add Mode:Guided mode guided
console menu add Mode:RTL mode rtl
```

Allow adding of menus on console

---

MAVProxy/modules/mavproxy_rcsetup.py

Not sure if `RC_CHANNELS_RAW` is a thing anymore

Calibrate RC with the proper MavLink message

---

MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_map/__init__.py

- can right-click-menu-item add a return point
- can remove that return point with a right-click on the point

Add manipulation of return point location

---

MAVProxy/modules/mavproxy_ftp.py

allow user to see bug https://github.com/ArduPilot/ardupilot/pull/24633
note that you can work around the bug with "set source_component 190" to match MissionPlanner

ftp: warn of incorrect component ID

---

MAVProxy/modules/mavproxy_SIYI.py

for basic control of a SIYI camera

added SIYI camera module

---

MAVProxy/modules/lib/param_help.py

param: show unknown bits in bitmasks

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_SIYI.py
MAVProxy/modules/mavproxy_map/__init__.py

SIYI: more commands

---

MAVProxy/modules/mavproxy_SIYI.py

SIYI: added PI controller

---

MAVProxy/modules/lib/mp_image.py
MAVProxy/modules/mavproxy_SIYI/__init__.py
MAVProxy/modules/mavproxy_SIYI/camera_view.py

- temperature on mouse movement
- click targetting mode
- more context menus
- use gstreamer pipeline for display

SIYI: more features

---

MAVProxy/modules/lib/mp_image.py
MAVProxy/modules/mavproxy_SIYI/__init__.py
MAVProxy/modules/mavproxy_SIYI/camera_view.py

SIYI: added object tracking

---

MAVProxy/tools/MAVExplorer.py

tlog can have duplicate blocks

MAVExplorer: fixed parameter extraction from ftp in tlog

---

MAVProxy/modules/lib/grapher.py

show millisecond when zoomed in, both with single and double axis

grapher: improved tick formatting

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_SIYI/__init__.py
MAVProxy/modules/mavproxy_fakegps.py
MAVProxy/modules/mavproxy_vicon.py

use common gps time function

---

MAVProxy/modules/mavproxy_map/__init__.py

so:
"map icon" to drop a flag at the current click location
"map icon barrell.png" to drop a barrell at the current click location

mavproxy_map: allow 'map icon' to take from current click location

---

MAVProxy/mavproxy.py

mavproxy.py: add 'click show' to print current click position

---

MAVProxy/modules/lib/magfit.py

this allows the orientation to be changed to find right orientation from a log

magfit: allow changing compass orientation

---

MAVProxy/modules/mavproxy_gimbal.py

ArduPilot stopped supporting gimbal_control

mavproxy_gimbal: use gimbal_manager_set_attitude for rate subcommand

---

MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py

use: map set font_size 1
default size is 0.5

map: added font size map setting

---

MAVProxy/modules/mavproxy_chat/chat_voice_to_text.py
MAVProxy/modules/mavproxy_chat/chat_window.py

Modified chat_voice_to_text.py to use the API Key set in the GUI's MENU in order to unify the API Key setting method.

Chat: improved API key setting method

---

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py

map: add altitude information to click data

---

MAVProxy/modules/lib/grapher.py
MAVProxy/tools/MAVExplorer.py

better for publication to separate the mode legend

grapher: allow show_flightmode = 0,1,2

---

MAVProxy/modules/lib/mp_instructor.py
MAVProxy/modules/mavproxy_instructor.py

Instructor station for SITL.
this module in intended for GCS pilot training using SITL.  (where the actual GCS pilot is using another GCS, connected to SITL.)
It can easily spoof/change key parameters to simulate different scenarios as well as help train the overall flight monitoring.

new module: instructor station

---

MAVProxy/tools/MAVExplorer.py

allows handling of mis-identified vehicle

MAVExplorer: added vehicle_type setting

---

MAVProxy/modules/lib/wxrc.py

If a user has configured 32 servo outputs (instead of the usual 16), the GUI now adds the extra outputs to the display.

Modules: RC GUI can now show 32 servo outputs

---

MAVProxy/modules/lib/camera_projection.py
MAVProxy/modules/lib/wxconsole_ui.py
MAVProxy/modules/mavproxy_SIYI/__init__.py

SIYI: add and use camera projection object

---

MAVProxy/modules/lib/mp_module.py
MAVProxy/modules/mavproxy_SIYI/__init__.py
MAVProxy/modules/mavproxy_silvus.py

prevent incorrect packet loss display

SIYI: fixed named float send sequence number

---

MAVProxy/modules/mavproxy_wp.py

allows user to create missions before GPS lock and home

wp: allow mission creation without home

---

MAVProxy/modules/mavproxy_map/__init__.py

... too hard to see width 1 on a sunny day

map: add setting for drawn circle thickness

---

MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_kmlread.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py

Allows the kml module to work without the map loaded.
When the map is loaded we populate layers based on the KML layers.
Based on several other PRS....

Make mavproxy_kmlread interact more nicely with mavproxy_map

---

MAVProxy/mavproxy.py

Matches what we output in the map display

mavproxy.py: increase precision of click show

---

MAVProxy/modules/mavproxy_param.py

make and mark parameter module flake8-clean

mavproxy_param: make it flake8-clean

---

MAVProxy/tools/mavflightview.py

.... and any instance with more than one digit....

mavflightview.py: correct mapping of XKF1[100]

---

MAVProxy/modules/lib/mission_item_protocol.py
MAVProxy/modules/mavproxy_fence.py
MAVProxy/modules/mavproxy_rally.py

mavproxy_fence/rally: flake8 cleanliness

modules: mission_item_protocol.py: flake8 compliance

---

MAVProxy/modules/mavproxy_console.py

I've tested that each message is still updating the interface.

mavproxy_console: factor console handling of mavlink messages

---

MAVProxy/modules/mavproxy_optitrack/DataDescriptions.py
MAVProxy/modules/mavproxy_optitrack/MoCapData.py
MAVProxy/modules/mavproxy_optitrack/NatNetClient.py
MAVProxy/modules/mavproxy_optitrack/__init__.py

Thank Leander Ullmann for testing Motive 3 supporting

mavproxy_optitrack: support Motive 3

---

MAVProxy/modules/mavproxy_nmeaout.py

nmeaout: correct module name

---

MAVProxy/modules/mavproxy_help.py

xmlrpc is no longer available on pypi
Use the JSON interface instead

Fix help module

---

MAVProxy/modules/mavproxy_messagerate.py

mavproxy_messagerate: do special handling for reset and stop set

---

MAVProxy/modules/mavproxy_map/mp_slipmap_util.py

... by moving loop invariant calculations to outside loop

mp_slipmap_util.py: tidy calculation of gridlines

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_output.py

makes using the support proxy with TCP much nicer

fixed auto reconnect on TCP connections

---

MAVProxy/modules/mavproxy_SIYI/__init__.py
MAVProxy/modules/mavproxy_SIYI/camera_view.py
MAVProxy/modules/mavproxy_SIYI/raw_thermal.py

some improvements from recent tests

SIYI: flight test fixes

---

MAVProxy/modules/lib/mp_util.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/modules/mavproxy_paramedit/param_editor_frame.py
MAVProxy/tools/MAVExplorer.py

this makes SERVO2_FUNCTION come after SERVO11_FUNCTION

param: sort parameters with 'natural' sort

---

MAVProxy/modules/mavproxy_warning.py

Add module to give audio warnings.

Add Warning module

---

MAVProxy/mavproxy.py
MAVProxy/modules/mavproxy_param.py
MAVProxy/tools/mavflightview.py

Became a lot touchier about global keyword!

Flake8 fixes for new version of flake8

---

MAVProxy/modules/mavproxy_wp.py

Found in https://github.com/ArduPilot/MAVProxy/pull/1533#issuecomment-2781272742

Fix no master when getting home

---

MAVProxy/modules/mavproxy_adsb.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py

settable colors, with alt threshold for changing color

adsb: improved alt display on vehicles

---

MAVProxy/modules/mavproxy_warning.py

warning: improved status, airspeed and display

---

MAVProxy/modules/mavproxy_ais.py

mavproxy_ais.py: use blue vehicle, correct returning of threat radius

---

MAVProxy/modules/mavproxy_misc.py

falls back to the mission item way if we get UNSUPPORTED

mavproxy_misc: add support for MAV_CMD_DO_CHANGE_ALTITUDE

---

MAVProxy/modules/lib/mp_module.py
MAVProxy/modules/mavproxy_silvus.py

silvus: fixes for streamcaster v5

---

MAVProxy/tools/MAVExplorer.py

useful for flight review vs a kml file

MAVExplorer: allow display of kml files

---

MAVProxy/modules/lib/mp_util.py

same driver is used for multiple different GPS types

mp_util.py: tweak AK09916 to AK0991x

---

MAVProxy/modules/mavproxy_ucenter.py

ucenter: fix for python3

---

MAVProxy/mavproxy.py

when forwarding an unsigned message from a downstream link to an upstream link that has signing enabled then re-pack the message to sign it.
This allows for tools like DroneCAN GUI tool to be used more easily

sign forwarded messages

---

MAVProxy/modules/lib/mission_item_protocol.py

with the change to the all dialect we can't reference the ardupilotmega dialect directly

mission: fixed WP moves

---

MAVProxy/modules/mavproxy_signing.py

if a link is down for more than 60 seconds then our signing timestamp can fall outside the acceptance window allowed on the server. This ensures we update to keep it within the window for when the link recovers

signing: ensure signing timestamps don't fall behind

---

MAVProxy/modules/mavproxy_kmlgen.py

allows for waypoint editing with google earth. The waypoint display auto-updates as you edit the mission

kmlgen: module to allow live viewing in google earth

---

MAVProxy/modules/mavproxy_link.py

when doing continous zoom it was spamming the console

link: suppress some camera acks

---

MAVProxy/modules/lib/rline.py
windows/MAVProxyWinBuild.bat
windows/mavproxy.spec

windows: try to fix error loading future

---

MAVProxy/mavproxy.py

this allows websocket connections to safely reconnect

cope with a link being in reconnecting state

---

MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py

Shows the grid spacing size when grid is enabled.

map: Show grid spacing

---

MAVProxy/modules/lib/MacOS/backend_agg.py
MAVProxy/modules/lib/MacOS/backend_wx.py
MAVProxy/modules/lib/MacOS/backend_wxagg.py
MAVProxy/modules/lib/mp_image.py
MAVProxy/modules/lib/rline.py
MAVProxy/modules/lib/wavefront.py
MAVProxy/modules/lib/win_layout.py
MAVProxy/modules/mavproxy_dataflash_logger.py
MAVProxy/modules/mavproxy_firmware.py
MAVProxy/modules/mavproxy_joystick/__init__.py
MAVProxy/modules/mavproxy_joystick/findjoy.py
MAVProxy/modules/mavproxy_magical/__init__.py
MAVProxy/modules/mavproxy_magical/wxgeodesicgrid.py
MAVProxy/modules/mavproxy_magical/wxvehicle.py
MAVProxy/modules/mavproxy_timesync.py
MAVProxy/tools/MAVExplorer.py
setup.py
windows/MAVProxyWinBuild.bat
windows/mavproxy.spec

Remove future import from many python files

---

MAVProxy/modules/mavproxy_map/GAreader.py
MAVProxy/modules/mavproxy_map/__init__.py
MAVProxy/modules/mavproxy_map/mp_elevation.py
MAVProxy/modules/mavproxy_map/mp_slipmap.py
MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
MAVProxy/modules/mavproxy_map/mp_slipmap_util.py
MAVProxy/modules/mavproxy_map/mp_tile.py
MAVProxy/modules/mavproxy_map/srtm.py

not 100% yet, these are the easy bits - just whitespace, unused imports "not x in y" -> "x not in y" etc etc.
Follow-up PR will deal with the remaining import problems.
Tested in SITL.

mavproxy_map: flake8 correctness

---

MAVProxy/tools/MAVExplorer.py

Allows dump to work with instance ids. 
Not sure if we want tab complete to also show the instance ids?

MAVExplorer: allow dump to work with instance ids, also update dump's usage text

---

MAVProxy/modules/mavproxy_misc.py

Allows a repeat command to be toggled rather than remove-then-add.
Updates the list to print the current state of each of the RepeatCommands.

misc: add toggleable repeat commands

---

MAVProxy/modules/mavproxy_map/mp_tile.py

the update replaces the older sources for the Norwegian maps

Updated maps for norway
